Webservinho: WebServer Class Reference
WebServer Class Reference
#include <init/WebServer.hpp>
Public Member Functions
void addToPollFD (int fd, short events)
Adds a file descriptor to the monitored poll vector.
int getPollTimeout (void)
Returns poll() timeout value depending on CGI activity.
void gracefulShutdown (void)
Sends shutdown notice to clients and closes all sockets.
void queueClientConnections (ServerSocket &socket)
Accepts new client connections on a given listening socket.
void receiveRequest (std::size_t i)
Handles incoming data from a connected client.
void removeClientConnection (int clientFD, size_t pollFDIndex)
Removes a client connection and cleans up associated poll entry.
void runServer (void)
Main event loop — monitors sockets, dispatches requests, and handles responses.
void sendResponse (std::size_t i)
Sends buffered response data to a connected client.
void startServer (void)
Initializes and binds all listening sockets defined in the configuration.
WebServer (Config const &config)
Constructs a WebServer instance with parsed configuration.
~WebServer (void)
Destructor — closes all sockets and cleans up client/state structures.
Private Member Functions
void addCgiPollFd (int cgiFd)
Adds a CGI pipe descriptor to the poll list for monitoring output.
void handleCgiReadable (int pollIndex)
Reads CGI process output and assembles it into the client buffer.
WebServer & operator= (WebServer const &rhs)
void removeCgiPollFd (int cgiFd)
Removes a CGI FD from poll() monitoring.
void sweepCgiTimeouts ()
Scans active CGI processes and terminates those exceeding timeout.
WebServer (WebServer const &src)
Private Attributes
std::map< int, int > _cgiFdToClientFd
std::map< int, CgiProcess > _cgiMap
std::map< int, ClientConnection > _clients
Config const & _config
std::vector< struct pollfd > _pollFDs
std::vector< ServerSocket * > _serverSocket
std::map< int, size_t > _socketToServerIndex
Detailed Description
Definition at line 15 of file WebServer.hpp.
Constructor & Destructor Documentation
WebServer() [1/2]
WebServer::WebServer (WebServer const & src) private
WebServer() [2/2]
WebServer::WebServer (Config const & config)
Constructs a WebServer instance with parsed configuration.
Initializes internal state and associates configuration objects for later socket and client setup.
Parameters
config Parsed configuration container.
Definition at line 26 of file WebServer.cpp.
    : _config(config), _serverSocket()
{
    Logger::instance().log(INFO, "WebServer: constructed");
}
References INFO, Logger::instance(), and Logger::log().
~WebServer()
WebServer::~WebServer (void)
Destructor — closes all sockets and cleans up client/state structures.
Definition at line 35 of file WebServer.cpp.
{
    Logger::instance().log(INFO, "WebServer: shutting down");
    for (std::map<int, ClientConnection>::iterator it = _clients.begin(); it != _clients.end(); ++it)
        ::close(it->first);
    _clients.clear();
    _pollFDs.clear();
    for (size_t i = 0; i < _serverSocket.size(); ++i)
    {
        if (_serverSocket[i])
        {
            delete _serverSocket[i];
            _serverSocket[i] = NULL;
        }
    }
    _serverSocket.clear();
    Logger::instance().log(INFO, "WebServer: cleanup complete");
}
References _clients, _pollFDs, _serverSocket, INFO, Logger::instance(), and Logger::log().
Member Function Documentation
addCgiPollFd()
void WebServer::addCgiPollFd (int cgiFd) private
Adds a CGI pipe descriptor to the poll list for monitoring output.
Definition at line 436 of file WebServer.cpp.
{
    int flags = ::fcntl(cgiFd, F_GETFL, 0);
    if (flags != -1)
        ::fcntl(cgiFd, F_SETFL, flags | O_NONBLOCK);
    struct pollfd pfd;
    pfd.fd = cgiFd;
    pfd.events = POLLIN | POLLHUP | POLLERR | POLLRDHUP | POLLNVAL;
    pfd.revents = 0;
    _pollFDs.push_back(pfd);
}
References _pollFDs.
Referenced by receiveRequest().
addToPollFD()
void WebServer::addToPollFD (int fd, short events)
Adds a file descriptor to the monitored poll vector.
Definition at line 278 of file WebServer.cpp.
{
    struct pollfd pfd;
    pfd.fd = fd;
    pfd.events = events;
    pfd.revents = 0;
    _pollFDs.push_back(pfd);
}
References _pollFDs.
Referenced by queueClientConnections(), and startServer().
getPollTimeout()
int WebServer::getPollTimeout (void)
Returns poll() timeout value depending on CGI activity.
Definition at line 290 of file WebServer.cpp.
{
    if (!_cgiFdToClientFd.empty())
        return 100; //100ms
    return 1000; //1s
}
References _cgiFdToClientFd.
Referenced by runServer().
gracefulShutdown()
void WebServer::gracefulShutdown (void)
Sends shutdown notice to clients and closes all sockets.
Called on graceful termination (SIGINT). Sends HTTP 503 responses before closing all connections.
Definition at line 304 of file WebServer.cpp.
{
    Logger::instance().log(INFO, "[Graceful shutdown initiated]");
    for (size_t i = 0; i < _serverSocket.size(); ++i)
        ::close(_serverSocket[i]->getFD());
    for (std::map<int, ClientConnection>::iterator it = _clients.begin(); it != _clients.end(); ++it)
    {
        int fd = it->first;
        ::shutdown(fd, SHUT_RDWR);
        ::close(fd);
    }
    _clients.clear();
    _pollFDs.clear();
    _cgiFdToClientFd.clear();
    Logger::instance().log(INFO, "WebServer: graceful shutdown complete");
}
References _cgiFdToClientFd, _clients, _pollFDs, _serverSocket, INFO, Logger::instance(), and Logger::log().
Referenced by runServer().
handleCgiReadable()
void WebServer::handleCgiReadable (int pollIndex) private
Reads CGI process output and assembles it into the client buffer.
When the CGI completes, the response is finalized and queued for sending.
Definition at line 472 of file WebServer.cpp.
{
    int cgiFd = _pollFDs[pollIndex].fd;
    std::map<int,int>::iterator mapIt = _cgiFdToClientFd.find(cgiFd);
    if (mapIt == _cgiFdToClientFd.end())
    {
        removeCgiPollFd(cgiFd);
        return;
    }
    int clientFd = mapIt->second;
    std::map<int, ClientConnection>::iterator it = _clients.find(clientFd);
    if (it == _clients.end())
    {
        removeCgiPollFd(cgiFd);
        return;
    }
    ClientConnection& client = it->second;
    char buf[4096];
    for (;;)
    {
        ssize_t n = ::read(cgiFd, buf, sizeof(buf));
        if (n > 0)
        {
            client.cgiBuffer().append(buf, n);
            continue;
        }
        if (n == 0)
        {
            int st = 0;
            pid_t res = waitpid(client.getCgiPid(), &st, WNOHANG);
            if (res == 0)
                break;
            removeCgiPollFd(cgiFd);
            Signals::unregisterCgiProcess(client.getCgiPid());
            ResponseBuilder::handleCgiOutput(client.getResponse(), client.cgiBuffer());
            ResponseBuilder::build(client, client.getRequest(), client.getResponse());
            client.setResponseBuffer(ResponseBuilder::responseWriter(client.getResponse()));
            for (size_t i = 0; i < _pollFDs.size(); ++i)
            {
                if (_pollFDs[i].fd == clientFd)
                {
                    _pollFDs[i].events = POLLOUT;
                    _pollFDs[i].revents = 0;
                    break;
                }
            }
            client.clearCgi();
            return;
        }
        if (n <= 0)
            break;
    }
}
References _cgiFdToClientFd, _clients, _pollFDs, ResponseBuilder::build(), ClientConnection::cgiBuffer(), ClientConnection::clearCgi(), ClientConnection::getCgiPid(), ClientConnection::getRequest(), ClientConnection::getResponse(), ResponseBuilder::handleCgiOutput(), removeCgiPollFd(), ResponseBuilder::responseWriter(), ClientConnection::setResponseBuffer(), and Signals::unregisterCgiProcess().
Referenced by runServer().
operator=()
WebServer & WebServer::operator= (WebServer const & rhs) private
queueClientConnections()
void WebServer::queueClientConnections (ServerSocket & socket)
Accepts new client connections on a given listening socket.
Each accepted client is configured, added to _clients, and registered in _pollFDs for read monitoring.
Definition at line 94 of file WebServer.cpp.
{
    std::vector<int> newFDs = socket.acceptConnections();
    for (size_t j = 0; j < newFDs.size(); j++)
    {
        int newClientFD = newFDs[j];
        if (_clients.find(newClientFD) == _clients.end())
        {
            size_t serverIndex = _socketToServerIndex[socket.getFD()];
            const ServerConfig& config = _config.getServerConfig()[serverIndex];
            Logger::instance().log(DEBUG, "WebServer: new client connection FD -> " + toString(newClientFD));
            std::pair<std::map<int, ClientConnection>::iterator, bool> res =
                _clients.insert(std::make_pair(newClientFD, ClientConnection(config)));
            ClientConnection& conn = res.first->second;
            conn.adoptFD(newClientFD);
            addToPollFD(newClientFD, POLLIN);
        }
    }
}
References _clients, _config, _socketToServerIndex, ServerSocket::acceptConnections(), addToPollFD(), ClientConnection::adoptFD(), DEBUG, ServerSocket::getFD(), Config::getServerConfig(), Logger::instance(), Logger::log(), and toString().
Referenced by runServer().
receiveRequest()
void WebServer::receiveRequest (std::size_t i)
Handles incoming data from a connected client.
Reads available bytes from the socket, delegates parsing to RequestParse::handleRawRequest, and triggers request dispatch once a complete request is received.
Definition at line 128 of file WebServer.cpp.
{
    std::map<int, ClientConnection>::iterator it = _clients.find(_pollFDs[i].fd);
    if (it == _clients.end())
    {
        Logger::instance().log(ERROR, "WebServer::receiveRequest: unknown client fd=" + toString(_pollFDs[i].fd));
        return ;
    }
    ClientConnection& client = it->second;
    try
    {
        ssize_t bytesRecv = client.recvData();
        Logger::instance().log(DEBUG, "WebServer::receiveRequest bytesRecv=" + toString(bytesRecv));
        if (bytesRecv > 0 && client.completedRequest())
        {
            Logger::instance().log(DEBUG, "WebServer::receiveRequest: full request received");
            Dispatcher::dispatch(client);
            if (!client.hasCgi())
            {
                _pollFDs[i].events = POLLOUT;
                client.setSentBytes(0);
            }
            else
            {
                _cgiFdToClientFd[client.getCgiFd()] = client.getFD();
                addCgiPollFd(client.getCgiFd());
                _pollFDs[i].events = POLLIN;
                _pollFDs[i].revents = 0;
            }
        }
        else if (client.getRequest().getMeta().getExpectContinue())
        {
            client.setResponseBuffer("HTTP/1.1 100 Continue\r\n\r\n");
            _pollFDs[i].events = POLLOUT;
            client.setSentBytes(0);
            client.getRequest().getMeta().setExpectContinue(false);
        }
        else if (bytesRecv == 0)
        {
            Logger::instance().log(INFO, "WebServer::receiveRequest: client disconnected");
            removeClientConnection(client.getFD(), i);
        }
    }
    catch (const std::exception& e)
    {
        Logger::instance().log(ERROR, std::string("WebServer::receiveRequest exception -> ") + e.what());
        removeClientConnection(client.getFD(), i);
    }
}
References _cgiFdToClientFd, _clients, _pollFDs, addCgiPollFd(), ClientConnection::completedRequest(), DEBUG, Dispatcher::dispatch(), ERROR, ClientConnection::getCgiFd(), RequestMeta::getExpectContinue(), ClientConnection::getFD(), HttpRequest::getMeta(), ClientConnection::getRequest(), ClientConnection::hasCgi(), INFO, Logger::instance(), Logger::log(), ClientConnection::recvData(), removeClientConnection(), RequestMeta::setExpectContinue(), ClientConnection::setResponseBuffer(), ClientConnection::setSentBytes(), and toString().
Referenced by runServer().
removeCgiPollFd()
void WebServer::removeCgiPollFd (int cgiFd) private
Removes a CGI FD from poll() monitoring.
Definition at line 452 of file WebServer.cpp.
{
    for (size_t i = 0; i < _pollFDs.size(); ++i)
    {
        if (_pollFDs[i].fd == cgiFd)
        {
            _pollFDs.erase(_pollFDs.begin() + i);
            break;
        }
    }
    if (cgiFd >= 0)
        ::close(cgiFd);
    _cgiFdToClientFd.erase(cgiFd);
}
References _cgiFdToClientFd, and _pollFDs.
Referenced by handleCgiReadable(), removeClientConnection(), runServer(), and sweepCgiTimeouts().
removeClientConnection()
void WebServer::removeClientConnection (int clientFD, size_t pollFDIndex)
Removes a client connection and cleans up associated poll entry.
Definition at line 245 of file WebServer.cpp.
{
    Logger::instance().log(DEBUG, "Removing client fd=" + toString(clientFD));
    if (pollFDIndex < _pollFDs.size())
        _pollFDs.erase(_pollFDs.begin() + pollFDIndex);
    // closes clients socket
    if (clientFD >= 0)
    {
        ::shutdown(clientFD, SHUT_RDWR);
        ::close(clientFD);
    }
    // Remove any cgi fd
    for (std::map<int,int>::iterator it = _cgiFdToClientFd.begin();
         it != _cgiFdToClientFd.end(); )
    {
        if (it->second == clientFD)
        {
            int cgiFd = it->first;
            removeCgiPollFd(cgiFd);
            it = _cgiFdToClientFd.begin();
        } else
            ++it;
    }
    _clients.erase(clientFD);
}
References _cgiFdToClientFd, _clients, _pollFDs, DEBUG, Logger::instance(), Logger::log(), removeCgiPollFd(), and toString().
Referenced by receiveRequest(), runServer(), and sendResponse().
runServer()
void WebServer::runServer (void)
Main event loop — monitors sockets, dispatches requests, and handles responses.
Uses poll() for multiplexing sockets, manages CGI subprocesses, and performs cleanup on signals or timeouts.
Definition at line 331 of file WebServer.cpp.
{
    Logger::instance().log(INFO, "[Started] WebServer::runServer");
    while (!Signals::shouldStop())
    {
        if (_pollFDs.empty())
        {
            usleep(100 * 1000); // 100ms
            sweepCgiTimeouts();
            continue;
        }
        int timeout = getPollTimeout();
        int ready = ::poll(&_pollFDs[0], _pollFDs.size(), timeout);
        sweepCgiTimeouts();
        if (Signals::shouldStop())
            break;
        if (ready == -1)
        {
            if (errno == EINTR)
                continue;
            Logger::instance().log(ERROR, "poll() failed, continuing main loop");
            continue;
        }
        for (ssize_t i = _pollFDs.size() - 1; i >= 0; --i)
        {
            const int fd = _pollFDs[i].fd;
            const short re = _pollFDs[i].revents;
            if (!re)
                continue;
            // --- CGI PIPE HANDLING ---
            if (_cgiFdToClientFd.count(fd))
            {
                if (re & (POLLIN | POLLHUP | POLLRDHUP))
                    handleCgiReadable(i);
                else if (re & (POLLERR | POLLNVAL))
                {
                    removeCgiPollFd(fd);
                    int clientFd = _cgiFdToClientFd[fd];
                    std::map<int, ClientConnection>::iterator itc = _clients.find(clientFd);
                    if (itc != _clients.end())
                    {
                        ClientConnection& c = itc->second;
                        c.getResponse().setStatusCode(ResponseStatus::BadGateway);
                        ResponseBuilder::build(c, c.getRequest(), c.getResponse());
                        c.setResponseBuffer(ResponseBuilder::responseWriter(c.getResponse()));
                        for (size_t k = 0; k < _pollFDs.size(); ++k)
{
                            if (_pollFDs[k].fd == clientFd)
{
                                _pollFDs[k].events = POLLOUT;
                                break;
                            }
                        }
                        c.clearCgi();
                    }
                }
                continue;
            }
            // --- LISTEN SOCKET ---
            if (re & POLLIN)
            {
                std::map<int, size_t>::iterator itSrv = _socketToServerIndex.find(fd);
                if (itSrv != _socketToServerIndex.end()) {
                    queueClientConnections(*_serverSocket[itSrv->second]);
                    continue;
                }
            }
            // --- CLIENT SOCKET ---
            if (re & POLLIN)
            {
                std::map<int, ClientConnection>::iterator cit = _clients.find(fd);
                if (cit != _clients.end())
                    receiveRequest(i);
                continue;
            }
            if (re & (POLLERR | POLLHUP | POLLRDHUP | POLLNVAL))
            {
                std::map<int, ClientConnection>::iterator itc = _clients.find(fd);
                if (itc != _clients.end())
                    removeClientConnection(itc->second.getFD(), i);
                continue;
            }
            if (re & POLLOUT)
                sendResponse(i);
        }
    }
    gracefulShutdown();
    Logger::instance().log(INFO, "[Finished] WebServer::runServer");
}
References _cgiFdToClientFd, _clients, _pollFDs, _serverSocket, _socketToServerIndex, ResponseStatus::BadGateway, ResponseBuilder::build(), ClientConnection::clearCgi(), ERROR, getPollTimeout(), ClientConnection::getRequest(), ClientConnection::getResponse(), gracefulShutdown(), handleCgiReadable(), INFO, Logger::instance(), Logger::log(), queueClientConnections(), receiveRequest(), removeCgiPollFd(), removeClientConnection(), ResponseBuilder::responseWriter(), sendResponse(), ClientConnection::setResponseBuffer(), HttpResponse::setStatusCode(), Signals::shouldStop(), and sweepCgiTimeouts().
Referenced by main().
sendResponse()
void WebServer::sendResponse (std::size_t i)
Sends buffered response data to a connected client.
Definition at line 187 of file WebServer.cpp.
{
    Logger::instance().log(DEBUG, "[Started] WebServer::sendResponse");
    std::map<int, ClientConnection>::iterator it = _clients.find(_pollFDs[i].fd);
    if (it == _clients.end())
    {
        Logger::instance().log(WARNING, "WebServer::sendResponse: unknown FD " + toString(_pollFDs[i].fd));
        return ;
    }
    ClientConnection& client = it->second;
    try
    {
        size_t totalLen = client.getResponseBuffer().length();
        size_t sent = client.getSentBytes();
        size_t toSend = (totalLen > sent) ? (totalLen - sent) : 0;
        if (!toSend)
        {
            _pollFDs[i].events = POLLIN;
            _pollFDs[i].revents = 0;
            return ;
        }
        ssize_t bytesSent = client.sendData(client, sent, toSend);
        if (bytesSent > 0)
        {
            client.setSentBytes(sent + static_cast<size_t>(bytesSent));
            if (client.getSentBytes() == totalLen)
            {
                client.clearBuffer();
                client.setSentBytes(0);
                _pollFDs[i].events = POLLIN;
                if (!client.getKeepAlive())
                {
                    Logger::instance().log(INFO, "WebServer::sendResponse: closing connection (no keep-alive)");
                    removeClientConnection(it->second.getFD(), i);
                }
            }
        }
    }
    catch (const std::exception& e)
    {
        Logger::instance().log(ERROR, std::string("WebServer::sendResponse exception -> ") + e.what());
        removeClientConnection(client.getFD(), i);
    }
    Logger::instance().log(DEBUG, "[Finished] WebServer::sendResponse");
}
References _clients, _pollFDs, ClientConnection::clearBuffer(), DEBUG, ERROR, ClientConnection::getFD(), ClientConnection::getKeepAlive(), ClientConnection::getResponseBuffer(), ClientConnection::getSentBytes(), INFO, Logger::instance(), Logger::log(), removeClientConnection(), ClientConnection::sendData(), ClientConnection::setSentBytes(), toString(), and WARNING.
Referenced by runServer().
startServer()
void WebServer::startServer (void)
Initializes and binds all listening sockets defined in the configuration.
For each server block in the config, creates a listening socket, binds it to the specified interface and port, and registers it into poll().
Definition at line 65 of file WebServer.cpp.
{
    Logger::instance().log(INFO, "[Started] WebServer::startServer");
    for (size_t i = 0; i < _config.getServerConfig().size(); i++)
    {
        _serverSocket.push_back(new ServerSocket());
        ServerSocket* tmpSocket = _serverSocket.back();
        tmpSocket->startSocket(_config.getServerConfig()[i].getListenInterface().second);
        tmpSocket->listenConnections(SOMAXCONN);
        int fd = tmpSocket->getFD();
        _socketToServerIndex[fd] = i;
        addToPollFD(fd, POLLIN);
        Logger::instance().log(INFO, "WebServer: listening on FD " + toString(fd));
    }
    Logger::instance().log(INFO, "[Finished] WebServer::startServer");
}
References _config, _serverSocket, _socketToServerIndex, addToPollFD(), ServerSocket::getFD(), Config::getServerConfig(), INFO, Logger::instance(), ServerSocket::listenConnections(), Logger::log(), ServerSocket::startSocket(), and toString().
Referenced by main().
sweepCgiTimeouts()
void WebServer::sweepCgiTimeouts () private
Scans active CGI processes and terminates those exceeding timeout.
Definition at line 534 of file WebServer.cpp.
{
    std::time_t now = std::time(NULL);
    std::vector<int> toKill;
    for (std::map<int,int>::iterator it = _cgiFdToClientFd.begin();
            it != _cgiFdToClientFd.end(); ++it)
    {
        int cgiFd = it->first;
        int clientFd = it->second;
        std::map<int, ClientConnection>::iterator cit = _clients.find(clientFd);
        if (cit == _clients.end())
        {
            toKill.push_back(cgiFd);
            continue;
        }
        ClientConnection& c = cit->second;
        double elapsed = difftime(now, c.getCgiStart());
        if (elapsed >= Signals::CGI_TIMEOUT_SEC)
        {
            Logger::instance().log(WARNING, "CGI timeout, killing pid=" + toString(c.getCgiPid()));
            kill(c.getCgiPid(), SIGKILL);
            int st;
            waitpid(c.getCgiPid(), &st, 0);
            Signals::unregisterCgiProcess(c.getCgiPid());
            c.getResponse().setStatusCode(ResponseStatus::GatewayTimeout);
            ResponseBuilder::build(c, c.getRequest(), c.getResponse());
            c.setResponseBuffer(ResponseBuilder::responseWriter(c.getResponse()));
            for (size_t i = 0; i < _pollFDs.size(); ++i)
            {
                if (_pollFDs[i].fd == clientFd)
                {
                    _pollFDs[i].events = POLLOUT;
                    _pollFDs[i].revents = 0;
                    break;
                }
            }
            ::close(cgiFd);
            toKill.push_back(cgiFd);
            c.clearCgi();
        }
    }
    for (size_t i = 0; i < toKill.size(); ++i)
        removeCgiPollFd(toKill[i]);
}
References _cgiFdToClientFd, _clients, _pollFDs, ResponseBuilder::build(), Signals::CGI_TIMEOUT_SEC, ClientConnection::clearCgi(), ResponseStatus::GatewayTimeout, ClientConnection::getCgiPid(), ClientConnection::getCgiStart(), ClientConnection::getRequest(), ClientConnection::getResponse(), Logger::instance(), Logger::log(), removeCgiPollFd(), ResponseBuilder::responseWriter(), ClientConnection::setResponseBuffer(), HttpResponse::setStatusCode(), toString(), Signals::unregisterCgiProcess(), and WARNING.
Referenced by runServer().
Member Data Documentation
_cgiFdToClientFd
std::map<int,int> WebServer::_cgiFdToClientFd private
Definition at line 27 of file WebServer.hpp.
Referenced by getPollTimeout(), gracefulShutdown(), handleCgiReadable(), receiveRequest(), removeCgiPollFd(), removeClientConnection(), runServer(), and sweepCgiTimeouts().
_cgiMap
std::map<int, CgiProcess> WebServer::_cgiMap private
Definition at line 28 of file WebServer.hpp.
_clients
std::map<int, ClientConnection> WebServer::_clients private
Definition at line 21 of file WebServer.hpp.
Referenced by gracefulShutdown(), handleCgiReadable(), queueClientConnections(), receiveRequest(), removeClientConnection(), runServer(), sendResponse(), sweepCgiTimeouts(), and ~WebServer().
_config
Config const& WebServer::_config private
Definition at line 18 of file WebServer.hpp.
Referenced by queueClientConnections(), and startServer().
_pollFDs
std::vector<struct pollfd> WebServer::_pollFDs private
Definition at line 22 of file WebServer.hpp.
Referenced by addCgiPollFd(), addToPollFD(), gracefulShutdown(), handleCgiReadable(), receiveRequest(), removeCgiPollFd(), removeClientConnection(), runServer(), sendResponse(), sweepCgiTimeouts(), and ~WebServer().
_serverSocket
std::vector<ServerSocket*> WebServer::_serverSocket private
Definition at line 20 of file WebServer.hpp.
Referenced by gracefulShutdown(), runServer(), startServer(), and ~WebServer().
_socketToServerIndex
std::map<int, size_t> WebServer::_socketToServerIndex private
Definition at line 19 of file WebServer.hpp.
Referenced by queueClientConnections(), runServer(), and startServer().
The documentation for this class was generated from the following files:
init/WebServer.hpp
init/WebServer.cpp