Webservinho: ServerConfig Class Reference
ServerConfig Class Reference
#include <config/ServerConfig.hpp>
Public Member Functions
void addLocation (LocationConfig &location)
Adds a new LocationConfig to the server.
bool getAutoindex (void) const
std::size_t const & getClientMaxBodySize (void) const
std::map< int, std::string > const & getErrorPage (void) const
std::pair< std::string, std::string > const & getListenInterface (void) const
std::vector< LocationConfig > const & getLocationConfig (void) const
std::string const & getRoot (void) const
const LocationConfig & matchLocation (const std::string &uri) const
Finds the LocationConfig that best matches a given URI.
ServerConfig (ServerConfig const &src)
Copy constructor for ServerConfig.
ServerConfig (void)
Default constructor for ServerConfig.
void setAutoindex (bool)
Enables or disables autoindex globally for the server.
void setClientMaxBodySize (std::size_t)
Defines the maximum allowed body size (in bytes).
void setErrorPage (int, std::string)
Associates a custom error page with an HTTP status code.
void setIndexFile (std::string)
Sets the default index file (e.g., "index.html").
void setListenInterface (std::pair< std::string, std::string >)
Sets the listening interface for this server.
void setRoot (std::string)
Defines the root directory for this server.
~ServerConfig (void)
Destructor — no dynamic allocation used.
Private Member Functions
ServerConfig & operator= (ServerConfig const &rhs)
Private Attributes
bool _autoindex
std::size_t _clientMaxBodysize
std::map< int, std::string > _errorPage
std::string _indexFile
std::pair< std::string, std::string > _listenInterface
std::vector< LocationConfig > _locations
std::string _root
Detailed Description
Definition at line 12 of file ServerConfig.hpp.
Constructor & Destructor Documentation
ServerConfig() [1/2]
ServerConfig::ServerConfig (void)
Default constructor for ServerConfig.
Initializes default values:
listen interface: 0.0.0.0:8000
client max body size: 1 MB
autoindex: disabled
Definition at line 15 of file ServerConfig.cpp.
{
    this->_listenInterface = std::make_pair("*", "8000");
    this->_clientMaxBodysize = (1 * 1024 * 1024); // 1MB
    this->_autoindex = false;
}
References _autoindex, _clientMaxBodysize, and _listenInterface.
ServerConfig() [2/2]
ServerConfig::ServerConfig (ServerConfig const & src)
Copy constructor for ServerConfig.
Definition at line 25 of file ServerConfig.cpp.
    : _listenInterface(src._listenInterface),
      _root(src._root),
      _clientMaxBodysize(src._clientMaxBodysize),
      _errorPage(src._errorPage),
      _indexFile(src._indexFile),
      _autoindex(src._autoindex),
      _locations(src._locations)
{}
~ServerConfig()
ServerConfig::~ServerConfig (void)
Destructor — no dynamic allocation used.
Definition at line 38 of file ServerConfig.cpp.
{}
Member Function Documentation
addLocation()
void ServerConfig::addLocation (LocationConfig & location)
Adds a new LocationConfig to the server.
Definition at line 143 of file ServerConfig.cpp.
{
    this->_locations.push_back(location);
}
References _locations.
Referenced by ConfigParser::parseLocationBlock().
getAutoindex()
bool ServerConfig::getAutoindex (void) const
Returns
True if autoindex is globally enabled for the server.
Definition at line 75 of file ServerConfig.cpp.
{
    return (this->_autoindex);
}
References _autoindex.
Referenced by Router::isAutoIndex().
getClientMaxBodySize()
std::size_t const & ServerConfig::getClientMaxBodySize (void) const
Returns
Maximum allowed body size for requests, in bytes.
Definition at line 59 of file ServerConfig.cpp.
{
    return (this->_clientMaxBodysize);
}
References _clientMaxBodysize.
Referenced by RequestParse::handleRawRequest().
getErrorPage()
std::map< int, std::string > const & ServerConfig::getErrorPage (void) const
Returns
Map of HTTP error codes to custom error page paths.
Definition at line 67 of file ServerConfig.cpp.
{
    return (this->_errorPage);
}
References _errorPage.
Referenced by ResponseBuilder::errorPageConfig().
getListenInterface()
std::pair< std::string, std::string > const & ServerConfig::getListenInterface (void) const
Returns
The IP:port pair (e.g. ("*", "8080")).
Definition at line 43 of file ServerConfig.cpp.
{
    return (this->_listenInterface);
}
References _listenInterface.
getLocationConfig()
std::vector< LocationConfig > const & ServerConfig::getLocationConfig (void) const
Returns
Vector of all LocationConfig objects under this server.
Definition at line 83 of file ServerConfig.cpp.
{
    return (this->_locations);
}
References _locations.
getRoot()
std::string const & ServerConfig::getRoot (void) const
Returns
The root directory of the server block.
Definition at line 51 of file ServerConfig.cpp.
{
    return (this->_root);
}
References _root.
Referenced by ResponseBuilder::build(), Router::computeResolvedPath(), Dispatcher::dispatch(), Router::isUpload(), and Router::resolve().
matchLocation()
const LocationConfig & ServerConfig::matchLocation (const std::string & uri) const
Finds the LocationConfig that best matches a given URI.
Exact match is prioritized.
Fallback uses the longest prefix match.
Parameters
uri The requested URI (e.g. "/images/logo.png").
Returns
The most appropriate LocationConfig.
Definition at line 157 of file ServerConfig.cpp.
{
    const LocationConfig* best = &_locations[0];
    size_t bestLen = 0;
    for (size_t i = 0; i < _locations.size(); ++i)
    {
        const std::string& locPath = _locations[i].getPath();
        // Exact match
        if (locPath == uri)
            return _locations[i];
        // Longest prefix fallback
        if (startsWith(uri, locPath) && locPath.size() > bestLen)
        {
            best = &_locations[i];
            bestLen = locPath.size();
        }
    }
    return (*best);
}
References _locations, LocationConfig::getPath(), and startsWith().
Referenced by RequestParse::checkMethod(), Dispatcher::dispatch(), Router::isAutoIndex(), Router::isRedirect(), Router::isUpload(), and Router::resolve().
operator=()
ServerConfig & ServerConfig::operator= (ServerConfig const & rhs) private
setAutoindex()
void ServerConfig::setAutoindex (bool newAutoindex)
Enables or disables autoindex globally for the server.
Definition at line 135 of file ServerConfig.cpp.
{
    this->_autoindex = newAutoindex;
}
References _autoindex.
Referenced by ConfigParser::parseServerBlock().
setClientMaxBodySize()
void ServerConfig::setClientMaxBodySize (std::size_t newSize)
Defines the maximum allowed body size (in bytes).
Definition at line 109 of file ServerConfig.cpp.
{
    this->_clientMaxBodysize = newSize;
}
References _clientMaxBodysize.
Referenced by ConfigParser::parseClientBodySize().
setErrorPage()
void ServerConfig::setErrorPage (int code, std::string path)
Associates a custom error page with an HTTP status code.
Example: setErrorPage(404, "/errors/404.html");
Definition at line 119 of file ServerConfig.cpp.
{
    this->_errorPage[code] = path;
}
References _errorPage.
Referenced by ConfigParser::parseServerBlock().
setIndexFile()
void ServerConfig::setIndexFile (std::string newIndexFile)
Sets the default index file (e.g., "index.html").
Definition at line 127 of file ServerConfig.cpp.
{
    this->_indexFile = newIndexFile;
}
References _indexFile.
Referenced by ConfigParser::parseServerBlock().
setListenInterface()
void ServerConfig::setListenInterface (std::pair< std::string, std::string > newPair)
Sets the listening interface for this server.
Parameters
newPair A pair representing IP and port (e.g. {"127.0.0.1", "8080"}).
Definition at line 93 of file ServerConfig.cpp.
{
    this->_listenInterface = newPair;
}
References _listenInterface.
Referenced by ConfigParser::parseListenInterface().
setRoot()
void ServerConfig::setRoot (std::string newRoot)
Defines the root directory for this server.
Definition at line 101 of file ServerConfig.cpp.
{
    this->_root = newRoot;
}
References _root.
Referenced by ConfigParser::parseServerBlock().
Member Data Documentation
_autoindex
bool ServerConfig::_autoindex private
Definition at line 20 of file ServerConfig.hpp.
Referenced by getAutoindex(), ServerConfig(), and setAutoindex().
_clientMaxBodysize
std::size_t ServerConfig::_clientMaxBodysize private
Definition at line 17 of file ServerConfig.hpp.
Referenced by getClientMaxBodySize(), ServerConfig(), and setClientMaxBodySize().
_errorPage
std::map<int, std::string> ServerConfig::_errorPage private
Definition at line 18 of file ServerConfig.hpp.
Referenced by getErrorPage(), and setErrorPage().
_indexFile
std::string ServerConfig::_indexFile private
Definition at line 19 of file ServerConfig.hpp.
Referenced by setIndexFile().
_listenInterface
std::pair<std::string, std::string> ServerConfig::_listenInterface private
Definition at line 15 of file ServerConfig.hpp.
Referenced by getListenInterface(), ServerConfig(), and setListenInterface().
_locations
std::vector<LocationConfig> ServerConfig::_locations private
Definition at line 21 of file ServerConfig.hpp.
Referenced by addLocation(), getLocationConfig(), and matchLocation().
_root
std::string ServerConfig::_root private
Definition at line 16 of file ServerConfig.hpp.
Referenced by getRoot(), and setRoot().
The documentation for this class was generated from the following files:
config/ServerConfig.hpp
config/ServerConfig.cpp