Webservinho: Signals Class Reference
Signals Class Reference
#include <utils/Signals.hpp>
Public Member Functions
Signals (void)
Default constructor for Signals utility class.
~Signals (void)
Destructor for Signals.
Static Public Member Functions
static void checkCgiTimeouts (void)
Periodically checks for CGI timeouts and terminates those exceeding the limit.
static void childSignalHandle (int signal)
Handles SIGCHLD signals to clean up terminated child processes.
static bool hasActiveCgi (void)
Checks if there are currently active CGI processes.
static void registerCgiProcess (pid_t pid)
Registers a new active CGI process.
static void setupHandlers (void)
Registers signal handlers for SIGINT, SIGTERM, and SIGCHLD.
static bool shouldStop (void)
Checks whether a stop signal was received.
static void signalHandle (int signal)
Handles SIGINT and SIGTERM for graceful shutdown.
static void unregisterCgiProcess (pid_t pid)
Unregisters a finished CGI process.
Static Public Attributes
static const int CGI_TIMEOUT_SEC = 30
Static Private Attributes
static volatile std::sig_atomic_t g_shouldStop = 0
Detailed Description
Definition at line 9 of file Signals.hpp.
Constructor & Destructor Documentation
Signals()
Signals::Signals (void)
Default constructor for Signals utility class.
Definition at line 15 of file Signals.cpp.
{}
~Signals()
Signals::~Signals (void)
Destructor for Signals.
Definition at line 20 of file Signals.cpp.
{}
Member Function Documentation
checkCgiTimeouts()
void Signals::checkCgiTimeouts (void) static
Periodically checks for CGI timeouts and terminates those exceeding the limit.
Any CGI process that runs longer than CGI_TIMEOUT_SEC seconds is forcefully killed. Also removes its PID from the active CGI map.
Definition at line 96 of file Signals.cpp.
{
    std::time_t now = std::time(NULL);
    for (std::map<pid_t, std::time_t>::iterator it = g_activeCgis.begin(); it != g_activeCgis.end(); )
    {
        double elapsed = difftime(now, it->second);
        if (elapsed > Signals::CGI_TIMEOUT_SEC)
        {
            Logger::instance().log(WARNING,
                "Signals: killing CGI pid=" + toString(it->first) +
                " (timeout " + toString(Signals::CGI_TIMEOUT_SEC) + "s exceeded)");
            kill(it->first, SIGKILL);
            std::map<pid_t, std::time_t>::iterator toErase = it;
            ++it;
            g_activeCgis.erase(toErase);
        }
        else
            ++it;
    }
}
References CGI_TIMEOUT_SEC, g_activeCgis, Logger::instance(), Logger::log(), toString(), and WARNING.
childSignalHandle()
void Signals::childSignalHandle (int signal) static
Handles SIGCHLD signals to clean up terminated child processes.
Uses non-blocking waitpid() calls with WNOHANG to reap CGI processes and remove their PIDs from the active map.
Definition at line 43 of file Signals.cpp.
{
    (void)signal;
    int     status;
    pid_t   pid;
    while ((pid = waitpid(-1, &status, WNOHANG)) > 0)
        unregisterCgiProcess(pid);
}
References unregisterCgiProcess().
Referenced by setupHandlers().
hasActiveCgi()
bool Signals::hasActiveCgi (void) static
Checks if there are currently active CGI processes.
Returns
true if one or more CGIs are running, false otherwise.
Definition at line 85 of file Signals.cpp.
{
    return (!g_activeCgis.empty());
}
References g_activeCgis.
registerCgiProcess()
void Signals::registerCgiProcess (pid_t pid) static
Registers a new active CGI process.
Parameters
pid Process ID of the CGI script. Adds the PID to an internal map with its start timestamp.
Definition at line 59 of file Signals.cpp.
{
    g_activeCgis[pid] = std::time(NULL);
    Logger::instance().log(DEBUG, "Signals: registered CGI pid=" + toString(pid));
}
References DEBUG, g_activeCgis, Logger::instance(), Logger::log(), and toString().
Referenced by CgiHandler::startAsync().
setupHandlers()
void Signals::setupHandlers (void) static
Registers signal handlers for SIGINT, SIGTERM, and SIGCHLD.
Enables graceful shutdown and automatic cleanup of CGI child processes.
Definition at line 134 of file Signals.cpp.
{
    std::signal(SIGINT, Signals::signalHandle);
    std::signal(SIGTERM, Signals::signalHandle);
    std::signal(SIGCHLD, Signals::childSignalHandle);
    Logger::instance().log(INFO, "Signal handlers registered");
}
References childSignalHandle(), INFO, Logger::instance(), Logger::log(), and signalHandle().
shouldStop()
bool Signals::shouldStop (void) static
Checks whether a stop signal was received.
Returns
true if the shutdown flag is set, false otherwise.
Definition at line 124 of file Signals.cpp.
{
    return (g_shouldStop != 0);
}
References g_shouldStop.
Referenced by WebServer::runServer().
signalHandle()
void Signals::signalHandle (int signal) static
Handles SIGINT and SIGTERM for graceful shutdown.
Sets a global flag (g_shouldStop) to notify the main loop that the server should stop safely. Writes directly to stderr to ensure visibility even if logging fails.
Definition at line 29 of file Signals.cpp.
{
    (void)signal;
    g_shouldStop = 1;
    write(STDERR_FILENO, "\n[Signal] Graceful shutdown requested\n", 38);
    Logger::instance().log(INFO, "SIGINT received: graceful shutdown requested");
}
References g_shouldStop, INFO, Logger::instance(), and Logger::log().
Referenced by main(), and setupHandlers().
unregisterCgiProcess()
void Signals::unregisterCgiProcess (pid_t pid) static
Unregisters a finished CGI process.
Removes its entry from the internal active CGI map.
Definition at line 70 of file Signals.cpp.
{
    std::map<pid_t, std::time_t>::iterator it = g_activeCgis.find(pid);
    if (it != g_activeCgis.end())
    {
        Logger::instance().log(DEBUG, "Signals: unregistered CGI pid=" + toString(pid));
        g_activeCgis.erase(it);
    }
}
References DEBUG, g_activeCgis, Logger::instance(), Logger::log(), and toString().
Referenced by childSignalHandle(), WebServer::handleCgiReadable(), and WebServer::sweepCgiTimeouts().
Member Data Documentation
CGI_TIMEOUT_SEC
const int Signals::CGI_TIMEOUT_SEC = 30 static
Definition at line 17 of file Signals.hpp.
Referenced by checkCgiTimeouts(), CgiHandler::startAsync(), and WebServer::sweepCgiTimeouts().
g_shouldStop
volatile std::sig_atomic_t Signals::g_shouldStop = 0 static private
Definition at line 12 of file Signals.hpp.
Referenced by shouldStop(), and signalHandle().
The documentation for this class was generated from the following files:
utils/Signals.hpp
utils/Signals.cpp