Webservinho: HttpResponse Class Reference
HttpResponse Class Reference
#include <response/HttpResponse.hpp>
Public Member Functions
void addHeader (const std::string &name, const std::string &value)
Adds a header field to the HTTP response.
void appendBody (char c)
Appends a single character to the response body.
void appendBody (const std::string &body)
Appends text data to the response body.
const std::string & getBody (void) const
Returns the current response body.
const std::string & getHeader (const std::string &name) const
Retrieves a header value by name.
const std::map< std::string, std::string > & getHeaders (void) const
Returns all response headers as a constant reference.
const std::string & getHttpVersion (void) const
Returns the HTTP version of this response.
const std::string & getReasonPhrase (void) const
Returns the reason phrase associated with the status code.
ResponseStatus::code getStatusCode (void) const
Returns the current HTTP status code.
HttpResponse ()
Default constructor for HttpResponse.
bool isChunked (void) const
Returns true if response uses chunked transfer encoding.
void reset (void)
Resets the response to its default, empty state.
void setChunked (bool chunked)
Sets whether the response will use chunked transfer encoding.
void setReasonPhrase (const ResponseStatus::code &code)
Sets the textual reason phrase for a given status code.
void setStatusCode (const ResponseStatus::code &code)
Sets the HTTP status code and updates the corresponding reason phrase.
void setVersion (const std::string &version)
Defines the HTTP version string (e.g., "1.1").
~HttpResponse ()
Destructor for HttpResponse.
Private Member Functions
HttpResponse (const HttpResponse &rhs)
HttpResponse & operator= (const HttpResponse &rhs)
const std::string statusCodeToString (const ResponseStatus::code &code)
Converts an HTTP status code to its standard reason phrase string.
Private Attributes
std::string _body
bool _chunked
std::map< std::string, std::string > _headers
std::string _reasonPhrase
ResponseStatus::code _statusCode
std::string _version
Detailed Description
Definition at line 11 of file HttpResponse.hpp.
Constructor & Destructor Documentation
HttpResponse() [1/2]
HttpResponse::HttpResponse (const HttpResponse & rhs) private
HttpResponse() [2/2]
HttpResponse::HttpResponse ()
Default constructor for HttpResponse.
Initializes response with default HTTP/1.1 OK status and no headers.
Definition at line 9 of file HttpResponse.cpp.
{
    setStatusCode(ResponseStatus::OK);
    setVersion("1.1");
    setChunked(false);
}
References ResponseStatus::OK, setChunked(), setStatusCode(), and setVersion().
~HttpResponse()
HttpResponse::~HttpResponse ()
Destructor for HttpResponse.
Definition at line 19 of file HttpResponse.cpp.
{}
Member Function Documentation
addHeader()
void HttpResponse::addHeader (const std::string & name, const std::string & value)
Adds a header field to the HTTP response.
If the header already exists, the values are concatenated using a comma.
Definition at line 67 of file HttpResponse.cpp.
{
    std::map<std::string, std::string>::iterator it;
    it = this->_headers.find(name);
    if (it != _headers.end())
    {
        std::string current = it->second;
        std::string new_ = current + "," + value;
        _headers.erase(it);
        _headers[name] = new_;
    }
    else
        _headers[name] = value;
}
References _headers.
Referenced by ResponseBuilder::build(), AutoIndexHandler::handle(), UploadHandler::handle(), ResponseBuilder::handleCgiOutput(), ResponseBuilder::handleStaticPageOutput(), Router::isRedirect(), and ResponseBuilder::setMinimumHeaders().
appendBody() [1/2]
void HttpResponse::appendBody (char c)
Appends a single character to the response body.
Definition at line 57 of file HttpResponse.cpp.
{
    this->_body.push_back(c);
}
References _body.
appendBody() [2/2]
void HttpResponse::appendBody (const std::string & body)
Appends text data to the response body.
Definition at line 49 of file HttpResponse.cpp.
{
    this->_body += body;
}
References _body.
Referenced by AutoIndexHandler::handle(), UploadHandler::handle(), ResponseBuilder::handleCgiOutput(), and ResponseBuilder::handleStaticPageOutput().
getBody()
const std::string & HttpResponse::getBody (void) const
Returns the current response body.
Definition at line 154 of file HttpResponse.cpp.
{ return (this->_body); }
References _body.
Referenced by UploadHandler::handle(), and ResponseBuilder::responseWriter().
getHeader()
const std::string & HttpResponse::getHeader (const std::string & name) const
Retrieves a header value by name.
Definition at line 133 of file HttpResponse.cpp.
{
    std::map<std::string, std::string>::const_iterator c_it;
    c_it = this->_headers.find(name);
    if (c_it != this->_headers.end())
        return (c_it->second);
    return (name);
}
References _headers.
Referenced by Dispatcher::dispatch().
getHeaders()
const std::map< std::string, std::string > & HttpResponse::getHeaders (void) const
Returns all response headers as a constant reference.
Definition at line 146 of file HttpResponse.cpp.
{
    return (this->_headers);
}
References _headers.
Referenced by ResponseBuilder::responseWriter().
getHttpVersion()
const std::string & HttpResponse::getHttpVersion (void) const
Returns the HTTP version of this response.
Definition at line 125 of file HttpResponse.cpp.
{
    return (this->_version);
}
References _version.
Referenced by ResponseBuilder::responseWriter().
getReasonPhrase()
const std::string & HttpResponse::getReasonPhrase (void) const
Returns the reason phrase associated with the status code.
Definition at line 117 of file HttpResponse.cpp.
{
    return (this->_reasonPhrase);
}
References _reasonPhrase.
Referenced by ResponseBuilder::responseWriter().
getStatusCode()
ResponseStatus::code HttpResponse::getStatusCode (void) const
Returns the current HTTP status code.
Definition at line 109 of file HttpResponse.cpp.
{
    return (this->_statusCode);
}
References _statusCode.
Referenced by ResponseBuilder::build(), Router::checkErrorStatus(), ResponseBuilder::errorPageConfig(), and ResponseBuilder::responseWriter().
isChunked()
bool HttpResponse::isChunked (void) const
Returns true if response uses chunked transfer encoding.
Definition at line 159 of file HttpResponse.cpp.
{ return (this->_chunked); }
References _chunked.
Referenced by ResponseBuilder::responseWriter().
operator=()
HttpResponse & HttpResponse::operator= (const HttpResponse & rhs) private
reset()
void HttpResponse::reset (void)
Resets the response to its default, empty state.
Clears headers, body, and resets HTTP metadata.
Definition at line 95 of file HttpResponse.cpp.
{
    this->_statusCode = ResponseStatus::OK;
    this->_reasonPhrase.clear();
    this->_version.clear();
    this->_headers.clear();
    this->_body.clear();
    this->_chunked = false;
    Logger::instance().log(DEBUG, "HttpResponse::reset complete");
}
References _body, _chunked, _headers, _reasonPhrase, _statusCode, _version, DEBUG, Logger::instance(), Logger::log(), and ResponseStatus::OK.
Referenced by Dispatcher::dispatch().
setChunked()
void HttpResponse::setChunked (bool chunked)
Sets whether the response will use chunked transfer encoding.
Definition at line 85 of file HttpResponse.cpp.
{
    this->_chunked = chunked;
}
References _chunked.
Referenced by ResponseBuilder::handleStaticPageOutput(), HttpResponse(), and Router::isRedirect().
setReasonPhrase()
void HttpResponse::setReasonPhrase (const ResponseStatus::code & code)
Sets the textual reason phrase for a given status code.
Definition at line 33 of file HttpResponse.cpp.
{
    this->_reasonPhrase = statusCodeToString(code);
}
References _reasonPhrase, and statusCodeToString().
Referenced by ResponseBuilder::build(), and setStatusCode().
setStatusCode()
void HttpResponse::setStatusCode (const ResponseStatus::code & code)
Sets the HTTP status code and updates the corresponding reason phrase.
Definition at line 24 of file HttpResponse.cpp.
{
    this->_statusCode = code;
    setReasonPhrase(code);
}
References _statusCode, and setReasonPhrase().
Referenced by Dispatcher::dispatch(), ResponseBuilder::errorPageConfig(), AutoIndexHandler::handle(), DeleteHandler::handle(), StaticPageHandler::handle(), UploadHandler::handle(), ResponseBuilder::handleCgiOutput(), HttpResponse(), Router::isCgi(), Router::isRedirect(), Router::isStaticFile(), Router::isUpload(), Router::resolve(), WebServer::runServer(), and WebServer::sweepCgiTimeouts().
setVersion()
void HttpResponse::setVersion (const std::string & version)
Defines the HTTP version string (e.g., "1.1").
Definition at line 41 of file HttpResponse.cpp.
{
    this->_version = version;
}
References _version.
Referenced by ResponseBuilder::build(), and HttpResponse().
statusCodeToString()
const std::string HttpResponse::statusCodeToString (const ResponseStatus::code & code) private
Converts an HTTP status code to its standard reason phrase string.
Definition at line 164 of file HttpResponse.cpp.
{
    switch (code)
    {
        // 1xx
        case ResponseStatus::Continue:
            return ("Continue");
        case ResponseStatus::SwitchingProtocols:
            return ("Switching Protocols");
        // 2xx
        case ResponseStatus::OK:
            return ("OK");
        case ResponseStatus::Created:
            return ("Created");
        case ResponseStatus::Accepted:
            return ("Accepted");
        case ResponseStatus::NoContent:
            return ("No Content");
        case ResponseStatus::PartialContent:
            return ("Partial Content");
        // 3xx
        case ResponseStatus::MovedPermanently:
            return ("Moved Permanently");
        case ResponseStatus::Found:
            return ("Found");
        case ResponseStatus::SeeOther:
            return ("See Other");
        case ResponseStatus::NotModified:
            return ("Not Modified");
        case ResponseStatus::TemporaryRedirect:
            return ("Temporary Redirect");
        // 4xx
        case ResponseStatus::BadRequest:
            return ("Bad Request");
        case ResponseStatus::Unauthorized:
            return ("Unauthorized");
        case ResponseStatus::Forbidden:
            return ("Forbidden");
        case ResponseStatus::NotFound:
            return ("Not Found");
        case ResponseStatus::MethodNotAllowed:
            return ("Method Not Allowed");
        case ResponseStatus::RequestTimeout:
            return ("Request Timeout");
        case ResponseStatus::Conflict:
            return ("Conflict");
        case ResponseStatus::Gone:
            return ("Gone");
        case ResponseStatus::PayloadTooLarge:
            return ("Payload Too Large");
        case ResponseStatus::UriTooLong:
            return ("URI Too Long");
        case ResponseStatus::UnsupportedMediaType:
            return ("Unsupported Media Type");
        case ResponseStatus::ExpectationFailed:
            return ("Expectation Failed");
        // 5xx
        case ResponseStatus::InternalServerError:
            return ("Internal Server Error");
        case ResponseStatus::NotImplemented:
            return ("Not Implemented");
        case ResponseStatus::BadGateway:
            return ("Bad Gateway");
        case ResponseStatus::ServiceUnavailable:
            return ("Service Unavailable");
        case ResponseStatus::GatewayTimeout:
            return ("Gateway Timeout");
        case ResponseStatus::HttpVersionNotSupported:
            return ("HTTP Version Not Supported");
        default:
            return ("Unknown Status");
    }
}
References ResponseStatus::Accepted, ResponseStatus::BadGateway, ResponseStatus::BadRequest, ResponseStatus::Conflict, ResponseStatus::Continue, ResponseStatus::Created, ResponseStatus::ExpectationFailed, ResponseStatus::Forbidden, ResponseStatus::Found, ResponseStatus::GatewayTimeout, ResponseStatus::Gone, ResponseStatus::HttpVersionNotSupported, ResponseStatus::InternalServerError, ResponseStatus::MethodNotAllowed, ResponseStatus::MovedPermanently, ResponseStatus::NoContent, ResponseStatus::NotFound, ResponseStatus::NotImplemented, ResponseStatus::NotModified, ResponseStatus::OK, ResponseStatus::PartialContent, ResponseStatus::PayloadTooLarge, ResponseStatus::RequestTimeout, ResponseStatus::SeeOther, ResponseStatus::ServiceUnavailable, ResponseStatus::SwitchingProtocols, ResponseStatus::TemporaryRedirect, ResponseStatus::Unauthorized, ResponseStatus::UnsupportedMediaType, and ResponseStatus::UriTooLong.
Referenced by setReasonPhrase().
Member Data Documentation
_body
std::string HttpResponse::_body private
Definition at line 18 of file HttpResponse.hpp.
Referenced by appendBody(), appendBody(), getBody(), and reset().
_chunked
bool HttpResponse::_chunked private
Definition at line 19 of file HttpResponse.hpp.
Referenced by isChunked(), reset(), and setChunked().
_headers
std::map<std::string, std::string> HttpResponse::_headers private
Definition at line 17 of file HttpResponse.hpp.
Referenced by addHeader(), getHeader(), getHeaders(), and reset().
_reasonPhrase
std::string HttpResponse::_reasonPhrase private
Definition at line 15 of file HttpResponse.hpp.
Referenced by getReasonPhrase(), reset(), and setReasonPhrase().
_statusCode
ResponseStatus::code HttpResponse::_statusCode private
Definition at line 14 of file HttpResponse.hpp.
Referenced by getStatusCode(), reset(), and setStatusCode().
_version
std::string HttpResponse::_version private
Definition at line 16 of file HttpResponse.hpp.
Referenced by getHttpVersion(), reset(), and setVersion().
The documentation for this class was generated from the following files:
response/HttpResponse.hpp
response/HttpResponse.cpp