Webservinho: ServerSocket Class Reference
ServerSocket Class Reference
#include <init/ServerSocket.hpp>
Public Member Functions
std::vector< int > acceptConnections (void)
Accepts all pending incoming client connections (non-blocking).
int getFD (void)
Returns the socket file descriptor.
void listenConnections (int backlog)
Starts listening for incoming client connections.
ServerSocket (ServerSocket const &src)
Copy constructor — duplicates only the file descriptor value.
ServerSocket (void)
Default constructor — initializes the socket descriptor to -1.
void startSocket (std::string const &port)
Creates, binds, and configures a non-blocking server socket.
~ServerSocket (void)
Destructor — closes the socket if it is still open.
Private Member Functions
ServerSocket & operator= (ServerSocket const &rhs)
Private Attributes
int _fd
Detailed Description
Definition at line 10 of file ServerSocket.hpp.
Constructor & Destructor Documentation
ServerSocket() [1/2]
ServerSocket::ServerSocket (void)
Default constructor — initializes the socket descriptor to -1.
Definition at line 19 of file ServerSocket.cpp.
                               : _fd(-1)
{
    Logger::instance().log(DEBUG, "ServerSocket: constructed (fd=-1)");
}
References DEBUG, Logger::instance(), and Logger::log().
ServerSocket() [2/2]
ServerSocket::ServerSocket (ServerSocket const & src)
Copy constructor — duplicates only the file descriptor value.
Definition at line 27 of file ServerSocket.cpp.
                                                  : _fd(src._fd)
{
    Logger::instance().log(DEBUG, "ServerSocket: copy-constructed (fd=" + toString(_fd) + ")");
}
References _fd, DEBUG, Logger::instance(), Logger::log(), and toString().
~ServerSocket()
ServerSocket::~ServerSocket (void)
Destructor — closes the socket if it is still open.
Definition at line 35 of file ServerSocket.cpp.
{
    if (this->_fd != -1)
    {
        ::close(this->_fd);
        Logger::instance().log(DEBUG, "ServerSocket: closed socket fd=" + toString(_fd));
    }
}
References _fd, DEBUG, Logger::instance(), Logger::log(), and toString().
Member Function Documentation
acceptConnections()
std::vector< int > ServerSocket::acceptConnections (void)
Accepts all pending incoming client connections (non-blocking).
Each accepted socket is set to non-blocking mode before returning.
Returns
A vector containing the file descriptors of all accepted clients.
Definition at line 139 of file ServerSocket.cpp.
{
    std::vector<int>    newFDs;
    while (true)
    {
        struct sockaddr_storage clientAddr;
        socklen_t               addrSize = sizeof(clientAddr);
        int                     clientFD = ::accept(this->_fd, (struct sockaddr*)&clientAddr, &addrSize);
        if (clientFD == -1)
        {
            if (errno == EAGAIN || errno == EWOULDBLOCK)
                break;
            std::string errorMsg(strerror(errno));
            Logger::instance().log(ERROR, "ServerSocket::acceptConnections: accept failed: " + errorMsg);
            break;
        }
        if (::fcntl(clientFD, F_SETFL, O_NONBLOCK) == -1)
        {
            std::string errorMsg(strerror(errno));
            Logger::instance().log(WARNING, "ServerSocket::acceptConnections: failed to set non-blocking: " + errorMsg);
            ::close(clientFD);
            continue;
        }
        try
        {
            newFDs.push_back(clientFD);
            Logger::instance().log(DEBUG, "ServerSocket: accepted client FD=" + toString(clientFD));
        }
        catch (const std::exception& e)
        {
            Logger::instance().log(ERROR, std::string("ServerSocket::acceptConnections: exception -> ") + e.what());
            ::close(clientFD);
        }
    }
    return (newFDs);
}
References _fd, DEBUG, ERROR, Logger::instance(), Logger::log(), toString(), and WARNING.
Referenced by WebServer::queueClientConnections().
getFD()
int ServerSocket::getFD (void)
Returns the socket file descriptor.
Definition at line 185 of file ServerSocket.cpp.
{
    return (this->_fd);
}
References _fd.
Referenced by WebServer::queueClientConnections(), and WebServer::startServer().
listenConnections()
void ServerSocket::listenConnections (int backlog)
Starts listening for incoming client connections.
Parameters
backlog Maximum length of the pending connections queue.
Exceptions
std::runtime_error if listen() fails.
Definition at line 122 of file ServerSocket.cpp.
{
    if (::listen(this->_fd, backlog) == -1)
    {
        std::string errorMsg(strerror(errno));
        throw std::runtime_error("ServerSocket::listenConnections: listen failed: " + errorMsg);
    }
    Logger::instance().log(INFO, "ServerSocket: listening with backlog=" + toString(backlog));
}
References _fd, INFO, Logger::instance(), Logger::log(), and toString().
Referenced by WebServer::startServer().
operator=()
ServerSocket & ServerSocket::operator= (ServerSocket const & rhs) private
startSocket()
void ServerSocket::startSocket (std::string const & port)
Creates, binds, and configures a non-blocking server socket.
Uses getaddrinfo() to support both IPv4 and IPv6 and binds to the specified port. The socket is configured with SO_REUSEADDR and set to non-blocking mode.
Parameters
port Port number to bind the socket to (as string).
Exceptions
std::runtime_error on any system call failure.
Definition at line 53 of file ServerSocket.cpp.
{
    int             status;
    int             socketFD;
    struct addrinfo hints;
    struct addrinfo *servInfo;
    struct addrinfo *tmp;
    Logger::instance().log(INFO, "ServerSocket: initializing socket on port " + port);
    std::memset(&hints, 0, sizeof(hints));
    hints.ai_family = AF_UNSPEC;      // Allow IPv4 or IPv6
    hints.ai_socktype = SOCK_STREAM;  // TCP
    hints.ai_flags = AI_PASSIVE;      // Use local IP automatically
    status = ::getaddrinfo(NULL, port.c_str(), &hints, &servInfo);
    if (status != 0)
    {
        std::string errorMsg(gai_strerror(status));
        throw std::runtime_error("ServerSocket::startSocket: getaddrinfo failed: " + errorMsg);
    }
    for (tmp = servInfo; tmp != NULL; tmp = tmp->ai_next)
    {
        socketFD = ::socket(tmp->ai_family, tmp->ai_socktype, tmp->ai_protocol);
        if (socketFD == -1)
            continue;
        int yes = 1;
        if (::setsockopt(socketFD, SOL_SOCKET, SO_REUSEADDR, &yes, sizeof(yes)) != 0)
        {
            ::close(socketFD);
            ::freeaddrinfo(servInfo);
            std::string errorMsg(strerror(errno));
            throw std::runtime_error("ServerSocket::startSocket: setsockopt failed: " + errorMsg);
        }
        if (::bind(socketFD, tmp->ai_addr, tmp->ai_addrlen) == 0)
            break; // Successfully bound
        ::close(socketFD);
        socketFD = -1;
    }
    ::freeaddrinfo(servInfo);
    if (socketFD == -1)
    {
        std::string errorMsg(strerror(errno));
        throw std::runtime_error("ServerSocket::startSocket: bind failed: " + errorMsg);
    }
    if (::fcntl(socketFD, F_SETFL, O_NONBLOCK) == -1)
    {
        ::close(socketFD);
        std::string errorMsg(strerror(errno));
        throw std::runtime_error("ServerSocket::startSocket: fcntl failed: " + errorMsg);
    }
    this->_fd = socketFD;
    Logger::instance().log(INFO, "ServerSocket: successfully started on port " + port);
}
References _fd, INFO, Logger::instance(), and Logger::log().
Referenced by WebServer::startServer().
Member Data Documentation
_fd
int ServerSocket::_fd private
Definition at line 13 of file ServerSocket.hpp.
Referenced by acceptConnections(), getFD(), listenConnections(), ServerSocket(), startSocket(), and ~ServerSocket().
The documentation for this class was generated from the following files:
init/ServerSocket.hpp
init/ServerSocket.cpp