Webservinho: RequestParse Class Reference
RequestParse Class Reference
#include <request/RequestParse.hpp>
Static Public Member Functions
static void handleRawRequest (const std::string &rawRequest, HttpRequest &request, ServerConfig const &config)
Parses and processes raw HTTP request data incrementally.
Private Member Functions
RequestParse & operator= (const RequestParse &rhs)
RequestParse ()
RequestParse (const RequestParse &rhs)
~RequestParse ()
Static Private Member Functions
static void body (char c, HttpRequest &request, std::size_t maxBodySize)
Processes the message body for both fixed-length and chunked modes.
static void bodyChunked (char c, HttpRequest &request, std::size_t maxBodySize)
Handles Transfer-Encoding: chunked body parsing.
static void checkMethod (HttpRequest &request, ServerConfig const &config)
Validates if the HTTP method is allowed in the matched location block.
static std::string extractQueryString (const std::string uri)
Extracts the query string portion from a URI.
static void headers (const std::string &header, HttpRequest &request, std::size_t maxBodySize)
Parses individual HTTP header lines and updates metadata.
static bool isGreaterThanMaxBodySize (std::size_t size, std::size_t maxBodySize)
Compares body size against maximum allowed by server configuration.
static void method (const std::string &method, HttpRequest &request, ServerConfig const &config)
Determines the HTTP method and validates it against configuration.
static void requestLine (const std::string &str, HttpRequest &request, ServerConfig const &config)
Parses the HTTP request line (method, URI, version).
static void uri (const std::string str, HttpRequest &request)
Extracts and validates the request URI and query string.
Detailed Description
Definition at line 13 of file RequestParse.hpp.
Constructor & Destructor Documentation
RequestParse() [1/2]
RequestParse::RequestParse () private
~RequestParse()
RequestParse::~RequestParse () private
RequestParse() [2/2]
RequestParse::RequestParse (const RequestParse & rhs) private
Member Function Documentation
body()
void RequestParse::body (char c, HttpRequest & request, std::size_t maxBodySize) static private
Processes the message body for both fixed-length and chunked modes.
Definition at line 285 of file RequestParse.cpp.
{
    if (!req.getMeta().isChunked())
    {
        if ((req.getBody().size() & 0x3FFF) == 0) // log every ~16KB
        {
            Logger::instance().log(DEBUG,
                "Body progress: " + toString(req.getBody().size()) + "/" +
                toString(req.getMeta().getContentLength()));
        }
        req.appendBody(c);
        if (req.getBody().size() >= req.getMeta().getContentLength())
            req.setRequestState(RequestState::Complete);
    }
    else
    {
        bodyChunked(c, req, maxBodySize);
    }
}
References HttpRequest::appendBody(), bodyChunked(), RequestState::Complete, DEBUG, HttpRequest::getBody(), RequestMeta::getContentLength(), HttpRequest::getMeta(), Logger::instance(), RequestMeta::isChunked(), Logger::log(), HttpRequest::setRequestState(), and toString().
Referenced by handleRawRequest().
bodyChunked()
void RequestParse::bodyChunked (char c, HttpRequest & request, std::size_t maxBodySize) static private
Handles Transfer-Encoding: chunked body parsing.
Definition at line 310 of file RequestParse.cpp.
{
    std::string& buffer = req.getBuffer();
    std::string& chunkBuffer = req.getChunkBuffer();
    if (isGreaterThanMaxBodySize(req.getCurrentChunkSize(), maxBodySize))
    {
        req.setParseError(ResponseStatus::PayloadTooLarge);
        req.setRequestState(RequestState::Complete);
        return ;
    }
    // Waiting for CRLF separator after a chunk
    if (req.isExpectingChunkSeparator())
    {
        buffer.push_back(c);
        if (buffer.size() >= 2 &&
            buffer[buffer.size() - 2] == '\r' &&
            buffer[buffer.size() - 1] == '\n')
        {
            req.clearBuffer();
            req.setExpectingChunkSeparator(false);
            req.setParsingChunkSize(true);
        }
        else if (buffer.size() > 2)
        {
            req.setParseError(ResponseStatus::BadRequest);
            req.setRequestState(RequestState::Complete);
        }
        return ;
    }
    // Parsing current chunk size
    if (req.isParsingChunkSize())
    {
        buffer.push_back(c);
        if (buffer.size() >= 2 &&
            buffer[buffer.size() - 2] == '\r' &&
            buffer[buffer.size() - 1] == '\n')
        {
            int size = stringToHex(buffer.substr(0, buffer.size() - 2));
            req.clearBuffer();
            if (size < 0)
            {
                req.setParseError(ResponseStatus::BadRequest);
                req.setRequestState(RequestState::Complete);
                return ;
            }
            if (size == 0)
            {
                req.setRequestState(RequestState::Complete);
                return ;
            }
            req.setCurrentChunkSize(size);
            req.setParsingChunkSize(false);
        }
        return ;
    }
    // Reading current chunk body
    chunkBuffer.push_back(c);
    if ((int)chunkBuffer.size() == req.getCurrentChunkSize())
    {
        req.appendBody(chunkBuffer);
        req.clearChunkBuffer();
        req.setExpectingChunkSeparator(true);
    }
}
References HttpRequest::appendBody(), ResponseStatus::BadRequest, HttpRequest::clearBuffer(), HttpRequest::clearChunkBuffer(), RequestState::Complete, HttpRequest::getBuffer(), HttpRequest::getChunkBuffer(), HttpRequest::getCurrentChunkSize(), HttpRequest::isExpectingChunkSeparator(), isGreaterThanMaxBodySize(), HttpRequest::isParsingChunkSize(), ResponseStatus::PayloadTooLarge, HttpRequest::setCurrentChunkSize(), HttpRequest::setExpectingChunkSeparator(), HttpRequest::setParseError(), HttpRequest::setParsingChunkSize(), HttpRequest::setRequestState(), and stringToHex().
Referenced by body().
checkMethod()
void RequestParse::checkMethod (HttpRequest & request, ServerConfig const & config) static private
Validates if the HTTP method is allowed in the matched location block.
Definition at line 405 of file RequestParse.cpp.
{
    if (req.getMethod() == RequestMethod::INVALID)
        return ;
    const LocationConfig& location = config.matchLocation(req.getUri());
    std::vector<RequestMethod::Method> methods = location.getMethods();
    RequestMethod::Method m = req.getMethod();
    for (size_t i = 0; i < methods.size(); ++i)
    {
        if (methods[i] == m)
            return ;
    }
    req.setParseError(ResponseStatus::MethodNotAllowed);
}
References HttpRequest::getMethod(), LocationConfig::getMethods(), HttpRequest::getUri(), RequestMethod::INVALID, ServerConfig::matchLocation(), ResponseStatus::MethodNotAllowed, and HttpRequest::setParseError().
Referenced by method().
extractQueryString()
std::string RequestParse::extractQueryString (const std::string uri) static private
Extracts the query string portion from a URI.
Definition at line 386 of file RequestParse.cpp.
{
    std::string::size_type queryPos = uri.find('?');
    if (queryPos != std::string::npos)
        return (uri.substr(queryPos + 1));
    return ("");
}
References uri().
Referenced by uri().
handleRawRequest()
void RequestParse::handleRawRequest (const std::string & chunk, HttpRequest & req, ServerConfig const & config) static
Parses and processes raw HTTP request data incrementally.
Handles the entire HTTP request flow: request line, headers, and body. Supports both Content-Length and chunked transfer encoding.
Definition at line 19 of file RequestParse.cpp.
{
    req.appendRaw(chunk);
    std::string& rawRequest = req.getRaw();
    std::string& buffer = req.getBuffer();
    std::size_t i = 0;
    if (req.getState() == RequestState::Complete)
        return ;
    while (i < rawRequest.size() && req.getState() != RequestState::Complete)
    {
        // Handle request line and headers
        if (req.getState() < RequestState::Body)
        {
            char ch = rawRequest[i];
            if (ch == '\r')
            {
                if (i + 1 >= rawRequest.size())
                    break ;
                if (rawRequest[i + 1] != '\n')
                {
                    req.setParseError(ResponseStatus::BadRequest);
                    return ;
                }
                if (req.getState() == RequestState::RequestLine)
                {
                    if (!buffer.empty())
                        requestLine(buffer, req, config);
                    if (req.getParseError() != ResponseStatus::OK)
                    {
                        req.setRequestState(RequestState::Complete);
                        return ;
                    }
                    req.setRequestState(RequestState::Headers);
                }
                else
                {
                    if (buffer.empty())
                    {
                        // End of headers: determine next state
                        if (req.getMeta().getContentLength() == 0 && !req.getMeta().isChunked())
                            req.setRequestState(RequestState::Complete);
                        else
                            req.setRequestState(RequestState::Body);
                        req.clearBuffer();
                        i += 2;
                        continue ;
                    }
                    else
                    {
                        headers(buffer, req, config.getClientMaxBodySize());
                    }
                }
                req.clearBuffer();
                i += 2;
                continue ;
            }
            buffer.push_back(ch);
            ++i;
            continue ;
        }
        // Handle body (Content-Length or chunked)
        if (req.getState() == RequestState::Body)
        {
            body(rawRequest[i], req, config.getClientMaxBodySize());
            ++i;
        }
    }
    // Remove processed data from buffer
    if (i > 0)
        req.getRaw().erase(0, i);
    // Normalize chunked requests (for CGI or POST processing)
    if (req.getMeta().isChunked() && req.getState() == RequestState::Complete)
    {
        Logger::instance().log(DEBUG, "RequestParse: finalizing chunked body for CGI");
        req.getMeta().setChunked(false);
        req.getMeta().setContentLength(req.getBody().size());
        req.addHeader("content-length", toString(req.getBody().size()));
        if (req.hasHeader("transfer-encoding"))
            req.removeHeader("transfer-encoding");
    }
    Logger::instance().log(DEBUG,
        "RequestParse::handleRawRequest consumed=" + toString(i) + " remaining=" + toString(rawRequest.size()));
}
References HttpRequest::addHeader(), HttpRequest::appendRaw(), ResponseStatus::BadRequest, body(), RequestState::Body, HttpRequest::clearBuffer(), RequestState::Complete, DEBUG, HttpRequest::getBody(), HttpRequest::getBuffer(), ServerConfig::getClientMaxBodySize(), RequestMeta::getContentLength(), HttpRequest::getMeta(), HttpRequest::getParseError(), HttpRequest::getRaw(), HttpRequest::getState(), HttpRequest::hasHeader(), headers(), RequestState::Headers, Logger::instance(), RequestMeta::isChunked(), Logger::log(), ResponseStatus::OK, HttpRequest::removeHeader(), requestLine(), RequestState::RequestLine, RequestMeta::setChunked(), RequestMeta::setContentLength(), HttpRequest::setParseError(), HttpRequest::setRequestState(), and toString().
Referenced by ClientConnection::recvData().
headers()
void RequestParse::headers (const std::string & header, HttpRequest & request, std::size_t maxBodySize) static private
Parses individual HTTP header lines and updates metadata.
Definition at line 208 of file RequestParse.cpp.
{
    Logger::instance().log(DEBUG, "[Started] RequestParse::headers");
    std::string::size_type pos = buffer.find(":");
    if (pos == std::string::npos)
    {
        req.setParseError(ResponseStatus::BadRequest);
        req.setRequestState(RequestState::Complete);
        Logger::instance().log(ERROR, "RequestParse::headers BadRequest (missing colon)");
        return ;
    }
    std::string key = toLower(trim(buffer.substr(0, pos)));
    std::string value = trim((pos + 1 < buffer.size()) ? buffer.substr(pos + 1) : std::string());
    if (buffer.length() > MAX_HEADER_LINE)
    {
        req.setParseError(ResponseStatus::PayloadTooLarge);
        req.setRequestState(RequestState::Complete);
        Logger::instance().log(ERROR, "RequestParse::headers PayloadTooLarge");
        return ;
    }
    if (key == "host")
        req.getMeta().setHost(value);
    else if (key == "content-length")
    {
        long size = std::atol(value.c_str());
        if (isGreaterThanMaxBodySize(size, maxBodySize))
        {
            req.setParseError(ResponseStatus::PayloadTooLarge);
            req.setRequestState(RequestState::Complete);
            Logger::instance().log(ERROR, "RequestParse::headers Content-Length exceeds limit");
            return ;
        }
        req.getMeta().setContentLength(size);
    }
    else if (key == "transfer-encoding")
    {
        std::string v = toLower(value);
        if (v.find("chunked") != std::string::npos)
            req.getMeta().setChunked(true);
        else if (v != "identity")
        {
            req.setParseError(ResponseStatus::BadRequest);
            req.setRequestState(RequestState::Complete);
            Logger::instance().log(ERROR, "RequestParse::headers Unsupported transfer-encoding: " + value);
            return ;
        }
    }
    else if (key == "connection")
        req.getMeta().setConnectionClose(toLower(value) == "close");
    else if (key == "expect")
    {
        if (toLower(value) == "100-continue")
        {
            req.getMeta().setExpectContinue(true);
            Logger::instance().log(DEBUG, "RequestParse::headers Expect: 100-continue");
        }
        else
        {
            req.setParseError(ResponseStatus::BadRequest);
            req.setRequestState(RequestState::Complete);
            Logger::instance().log(ERROR, "RequestParse::headers BadRequest on Expect header");
            return ;
        }
    }
    req.addHeader(key, value);
    Logger::instance().log(DEBUG, "[Finished] RequestParse::headers");
}
References HttpRequest::addHeader(), ResponseStatus::BadRequest, RequestState::Complete, DEBUG, ERROR, HttpRequest::getMeta(), Logger::instance(), isGreaterThanMaxBodySize(), Logger::log(), MAX_HEADER_LINE, ResponseStatus::PayloadTooLarge, RequestMeta::setChunked(), RequestMeta::setConnectionClose(), RequestMeta::setContentLength(), RequestMeta::setExpectContinue(), RequestMeta::setHost(), HttpRequest::setParseError(), HttpRequest::setRequestState(), toLower(), and trim().
Referenced by handleRawRequest().
isGreaterThanMaxBodySize()
bool RequestParse::isGreaterThanMaxBodySize (std::size_t size, std::size_t maxBodySize) static private
Compares body size against maximum allowed by server configuration.
Definition at line 397 of file RequestParse.cpp.
{
    return (size > maxBodySize);
}
Referenced by bodyChunked(), and headers().
method()
void RequestParse::method (const std::string & method, HttpRequest & request, ServerConfig const & config) static private
Determines the HTTP method and validates it against configuration.
Definition at line 163 of file RequestParse.cpp.
{
    if (method == "GET")
        req.setMethod(RequestMethod::GET);
    else if (method == "POST")
        req.setMethod(RequestMethod::POST);
    else if (method == "DELETE")
        req.setMethod(RequestMethod::DELETE);
    else if (method == "PUT")
        req.setMethod(RequestMethod::PUT);
    else
    {
        req.setMethod(RequestMethod::INVALID);
        req.setParseError(ResponseStatus::MethodNotAllowed);
    }
    checkMethod(req, config);
}
References checkMethod(), RequestMethod::DELETE, RequestMethod::GET, RequestMethod::INVALID, method(), ResponseStatus::MethodNotAllowed, RequestMethod::POST, RequestMethod::PUT, HttpRequest::setMethod(), and HttpRequest::setParseError().
Referenced by method(), and requestLine().
operator=()
RequestParse & RequestParse::operator= (const RequestParse & rhs) private
requestLine()
void RequestParse::requestLine (const std::string & str, HttpRequest & request, ServerConfig const & config) static private
Parses the HTTP request line (method, URI, version).
Definition at line 118 of file RequestParse.cpp.
{
    Logger::instance().log(DEBUG, "[Started] RequestParse::reqLine");
    const std::vector<std::string> tokens = split(buffer, " ");
    if (tokens.size() != 3)
    {
        req.setParseError(ResponseStatus::BadRequest);
        return ;
    }
    uri(tokens[1], req);
    method(tokens[0], req, config);
    const std::string version = tokens[2];
    if (version.size() < 8 || version.substr(0, 5) != "HTTP/" || version.find('.') == std::string::npos)
    {
        req.setParseError(ResponseStatus::BadRequest);
        return ;
    }
    std::vector<std::string> parts = split(version.substr(5), ".");
    if (parts.size() != 2)
    {
        req.setParseError(ResponseStatus::BadRequest);
        return ;
    }
    if (parts[0] != "1" || parts[1] != "1")
    {
        req.setParseError(ResponseStatus::HttpVersionNotSupported);
        return ;
    }
    req.setMajor(std::atoi(parts[0].c_str()));
    req.setMinor(std::atoi(parts[1].c_str()));
    Logger::instance().log(DEBUG, "[Finished] RequestParse::reqLine");
}
References ResponseStatus::BadRequest, DEBUG, ResponseStatus::HttpVersionNotSupported, Logger::instance(), Logger::log(), method(), HttpRequest::setMajor(), HttpRequest::setMinor(), HttpRequest::setParseError(), split(), and uri().
Referenced by handleRawRequest().
uri()
void RequestParse::uri (const std::string str, HttpRequest & request) static private
Extracts and validates the request URI and query string.
Definition at line 185 of file RequestParse.cpp.
{
    std::string uri = str;
    std::string::size_type queryPos = uri.find('?');
    if (queryPos != std::string::npos)
        uri = str.substr(0, queryPos);
    if (uri.length() > MAX_URI)
    {
        Logger::instance().log(ERROR, "RequestParse::uri URI too long");
        req.setParseError(ResponseStatus::UriTooLong);
        req.setRequestState(RequestState::Complete);
        return ;
    }
    req.setUri(uri);
    req.setQueryString(extractQueryString(str));
}
References RequestState::Complete, ERROR, extractQueryString(), Logger::instance(), Logger::log(), MAX_URI, HttpRequest::setParseError(), HttpRequest::setQueryString(), HttpRequest::setRequestState(), HttpRequest::setUri(), uri(), and ResponseStatus::UriTooLong.
Referenced by extractQueryString(), requestLine(), and uri().
The documentation for this class was generated from the following files:
request/RequestParse.hpp
request/RequestParse.cpp