Webservinho: HttpRequest Class Reference
HttpRequest Class Reference
#include <request/HttpRequest.hpp>
Public Member Functions
void addHeader (const std::string &name, const std::string &value)
Adds or appends a header field to the internal map.
void appendBody (char c)
void appendBody (const std::string &body)
Appends data to the body of the request.
void appendRaw (const std::string &chunk)
Appends raw data to the internal request buffer.
void clearBuffer (void)
Clears the general parsing buffer.
void clearChunkBuffer (void)
Clears the temporary buffer used for chunked transfer decoding.
const std::map< std::string, std::string > & getAllHeaders (void) const
Returns a const reference to the full headers map.
const std::string & getBody (void) const
Returns the body of the request.
std::string & getBuffer (void)
std::string & getChunkBuffer (void)
int getCurrentChunkSize (void) const
const std::string & getHeader (const std::string &name) const
Retrieves a header value by name (case-insensitive).
const std::vector< int > getHttpVersion (void) const
Returns the HTTP version as a pair of integers (major, minor).
RequestMeta & getMeta (void)
const RequestMeta & getMeta (void) const
Returns a const reference to the RequestMeta structure.
RequestMethod::Method getMethod (void) const
Returns the current HTTP method.
ResponseStatus::code getParseError (void) const
Returns the HTTP parse error code (if any).
const std::string & getQueryString (void) const
std::string & getRaw (void)
Returns the raw request buffer (used during parsing).
const std::string getResolvedPath (void) const
Returns the resolved filesystem path corresponding to the URI.
RouteType::route getRouteType (void) const
RequestState::state getState (void) const
const std::string & getUri (void) const
bool hasHeader (const std::string &key) const
Checks whether a header with the given key exists.
HttpRequest ()
Constructs a new HttpRequest with default initialized state.
bool isExpectingChunkSeparator () const
bool isParsingChunkSize () const
const std::string methodToString (void) const
Converts the HTTP method enum to its string representation.
void removeHeader (const std::string &key)
Removes a header from the request by name.
void reset (void)
Resets the HttpRequest object to its initial state.
void setCurrentChunkSize (int size)
Updates the size of the current chunk being parsed.
void setExpectingChunkSeparator (bool value)
void setMajor (int major)
Sets the HTTP major version number.
void setMethod (const RequestMethod::Method &method)
Sets the HTTP request method.
void setMinor (int minor)
Sets the HTTP minor version number.
void setParseError (ResponseStatus::code reason)
void setParsingChunkSize (bool value)
void setQueryString (const std::string queryString)
Sets the query string extracted from the URI.
void setRequestState (RequestState::state state)
void setResolvedPath (const std::string path)
Sets the absolute filesystem path resolved from the URI.
void setRouteType (RouteType::route route)
void setUri (const std::string &uri)
Sets the request target URI.
~HttpRequest ()
Private Member Functions
HttpRequest (const HttpRequest &rhs)
HttpRequest & operator= (const HttpRequest &rhs)
Private Attributes
std::string _body
std::string _buffer
std::string _chunkBuffer
int _currentChunkSize
bool _expectingChunkSeparator
std::map< std::string, std::string > _headers
int _major
RequestMeta _meta
RequestMethod::Method _method
int _minor
ResponseStatus::code _parseError
bool _parsingChunkSize
std::string _queryString
std::string _rawRequest
std::string _resolvedPath
RouteType::route _route
RequestState::state _state
std::string _uri
Detailed Description
Definition at line 16 of file HttpRequest.hpp.
Constructor & Destructor Documentation
HttpRequest() [1/2]
HttpRequest::HttpRequest (const HttpRequest & rhs) private
HttpRequest() [2/2]
HttpRequest::HttpRequest ()
Constructs a new HttpRequest with default initialized state.
Sets default values for parsing, chunked transfer, and route type.
Definition at line 10 of file HttpRequest.cpp.
{
    setMethod(RequestMethod::INVALID);
    setParseError(ResponseStatus::OK);
    getMeta().setContentLength(0);
    getMeta().setChunked(false);
    getMeta().setConnectionClose(false);
    getMeta().setExpectContinue(false);
    getMeta().setRedirect(false);
    setRequestState(RequestState::RequestLine);
    setParsingChunkSize(true);
    setExpectingChunkSeparator(false);
    setCurrentChunkSize(0);
}
References getMeta(), RequestMethod::INVALID, ResponseStatus::OK, RequestState::RequestLine, RequestMeta::setChunked(), RequestMeta::setConnectionClose(), RequestMeta::setContentLength(), setCurrentChunkSize(), RequestMeta::setExpectContinue(), setExpectingChunkSeparator(), setMethod(), setParseError(), setParsingChunkSize(), RequestMeta::setRedirect(), and setRequestState().
~HttpRequest()
HttpRequest::~HttpRequest ()
Definition at line 25 of file HttpRequest.cpp.
{}
Member Function Documentation
addHeader()
void HttpRequest::addHeader (const std::string & name, const std::string & value)
Adds or appends a header field to the internal map.
If the header already exists, values are concatenated with commas.
Definition at line 60 of file HttpRequest.cpp.
{
    std::map<std::string, std::string>::iterator it;
    it = this->_headers.find(name);
    if (it != _headers.end())
    {
        std::string current = it->second;
        std::string new_ = current + "," + value;
        _headers.erase(it);
        _headers[name] = new_;
    }
    else
        _headers[name] = value;
}
References _headers.
Referenced by RequestParse::handleRawRequest(), and RequestParse::headers().
appendBody() [1/2]
void HttpRequest::appendBody (char c)
Definition at line 83 of file HttpRequest.cpp.
{
    this->_body.push_back(c);
}
References _body.
appendBody() [2/2]
void HttpRequest::appendBody (const std::string & body)
Appends data to the body of the request.
Definition at line 78 of file HttpRequest.cpp.
{
    this->_body += body;
}
References _body.
Referenced by RequestParse::body(), and RequestParse::bodyChunked().
appendRaw()
void HttpRequest::appendRaw (const std::string & chunk)
Appends raw data to the internal request buffer.
Definition at line 106 of file HttpRequest.cpp.
{
    this->_rawRequest += chunk;
}
References _rawRequest.
Referenced by RequestParse::handleRawRequest().
clearBuffer()
void HttpRequest::clearBuffer (void)
Clears the general parsing buffer.
Definition at line 114 of file HttpRequest.cpp.
{
    this->_buffer.clear();
}
References _buffer.
Referenced by RequestParse::bodyChunked(), and RequestParse::handleRawRequest().
clearChunkBuffer()
void HttpRequest::clearChunkBuffer (void)
Clears the temporary buffer used for chunked transfer decoding.
Definition at line 122 of file HttpRequest.cpp.
{
    this->_chunkBuffer.clear();
}
References _chunkBuffer.
Referenced by RequestParse::bodyChunked().
getAllHeaders()
const std::map< std::string, std::string > & HttpRequest::getAllHeaders (void) const
Returns a const reference to the full headers map.
Definition at line 248 of file HttpRequest.cpp.
{
    return (this->_headers);
}
References _headers.
Referenced by CgiHandler::buildEnvp().
getBody()
const std::string & HttpRequest::getBody (void) const
Returns the body of the request.
Definition at line 269 of file HttpRequest.cpp.
{
    return (this->_body);
}
References _body.
Referenced by RequestParse::body(), UploadHandler::handle(), RequestParse::handleRawRequest(), and CgiHandler::startAsync().
getBuffer()
std::string & HttpRequest::getBuffer (void)
Definition at line 300 of file HttpRequest.cpp.
{
    return (this->_buffer);
}
References _buffer.
Referenced by RequestParse::bodyChunked(), and RequestParse::handleRawRequest().
getChunkBuffer()
std::string & HttpRequest::getChunkBuffer (void)
Definition at line 305 of file HttpRequest.cpp.
{
    return (this->_chunkBuffer);
}
References _chunkBuffer.
Referenced by RequestParse::bodyChunked().
getCurrentChunkSize()
int HttpRequest::getCurrentChunkSize (void) const
Definition at line 310 of file HttpRequest.cpp.
{
    return (this->_currentChunkSize);
}
References _currentChunkSize.
Referenced by RequestParse::bodyChunked().
getHeader()
const std::string & HttpRequest::getHeader (const std::string & name) const
Retrieves a header value by name (case-insensitive).
Definition at line 234 of file HttpRequest.cpp.
{
    std::map<std::string, std::string>::const_iterator c_it;
    std::string norm_name = toLower(name);
    c_it = this->_headers.find(norm_name);
    if (c_it != this->_headers.end())
        return (c_it->second);
    return (name);
}
References _headers, and toLower().
Referenced by CgiHandler::buildEnvp(), and UploadHandler::handle().
getHttpVersion()
const std::vector< int > HttpRequest::getHttpVersion (void) const
Returns the HTTP version as a pair of integers (major, minor).
Definition at line 225 of file HttpRequest.cpp.
{
    int version[2] = {this->_major, this->_minor};
    return (std::vector<int>(version, version + 2));
}
References _major, and _minor.
getMeta() [1/2]
RequestMeta & HttpRequest::getMeta (void)
Definition at line 261 of file HttpRequest.cpp.
{
    return (this->_meta);
}
References _meta.
getMeta() [2/2]
const RequestMeta & HttpRequest::getMeta (void) const
Returns a const reference to the RequestMeta structure.
Definition at line 256 of file HttpRequest.cpp.
{
    return (this->_meta);
}
References _meta.
Referenced by RequestParse::body(), ResponseBuilder::build(), Dispatcher::dispatch(), RequestParse::handleRawRequest(), RequestParse::headers(), HttpRequest(), Router::isRedirect(), and WebServer::receiveRequest().
getMethod()
RequestMethod::Method HttpRequest::getMethod (void) const
Returns the current HTTP method.
Definition at line 183 of file HttpRequest.cpp.
{
    return (this->_method);
}
References _method.
Referenced by RequestParse::checkMethod(), AutoIndexHandler::handle(), Router::isUpload(), and Router::resolve().
getParseError()
ResponseStatus::code HttpRequest::getParseError (void) const
Returns the HTTP parse error code (if any).
Definition at line 277 of file HttpRequest.cpp.
{
    return (this->_parseError);
}
References _parseError.
Referenced by ClientConnection::completedRequest(), RequestParse::handleRawRequest(), and Router::resolve().
getQueryString()
const std::string & HttpRequest::getQueryString (void) const
Definition at line 220 of file HttpRequest.cpp.
{ return (this->_queryString); }
References _queryString.
Referenced by CgiHandler::buildEnvp().
getRaw()
std::string & HttpRequest::getRaw (void)
Returns the raw request buffer (used during parsing).
Definition at line 295 of file HttpRequest.cpp.
{
    return (this->_rawRequest);
}
References _rawRequest.
Referenced by RequestParse::handleRawRequest().
getResolvedPath()
const std::string HttpRequest::getResolvedPath (void) const
Returns the resolved filesystem path corresponding to the URI.
Definition at line 328 of file HttpRequest.cpp.
{
    return (this->_resolvedPath);
}
References _resolvedPath.
Referenced by CgiHandler::buildEnvp(), Dispatcher::dispatch(), AutoIndexHandler::handle(), DeleteHandler::handle(), StaticPageHandler::handle(), Router::isAutoIndex(), Router::isCgi(), Router::isStaticFile(), and CgiHandler::startAsync().
getRouteType()
RouteType::route HttpRequest::getRouteType (void) const
Definition at line 287 of file HttpRequest.cpp.
{
    return (this->_route);
}
References _route.
Referenced by Dispatcher::dispatch().
getState()
RequestState::state HttpRequest::getState (void) const
Definition at line 282 of file HttpRequest.cpp.
{
    return (this->_state);
}
References _state.
Referenced by ClientConnection::completedRequest(), and RequestParse::handleRawRequest().
getUri()
const std::string & HttpRequest::getUri (void) const
Definition at line 218 of file HttpRequest.cpp.
{ return (this->_uri); }
References _uri.
Referenced by CgiHandler::buildEnvp(), RequestParse::checkMethod(), Router::computeResolvedPath(), Dispatcher::dispatch(), AutoIndexHandler::handle(), Router::isAutoIndex(), Router::isRedirect(), Router::isUpload(), and Router::resolve().
hasHeader()
bool HttpRequest::hasHeader (const std::string & key) const
Checks whether a header with the given key exists.
Definition at line 336 of file HttpRequest.cpp.
{
    std::string lowerKey = toLower(key);
    return (_headers.find(lowerKey) != _headers.end());
}
References _headers, and toLower().
Referenced by RequestParse::handleRawRequest().
isExpectingChunkSeparator()
bool HttpRequest::isExpectingChunkSeparator (void) const
Definition at line 320 of file HttpRequest.cpp.
{
    return (this->_expectingChunkSeparator);
}
References _expectingChunkSeparator.
Referenced by RequestParse::bodyChunked().
isParsingChunkSize()
bool HttpRequest::isParsingChunkSize (void) const
Definition at line 315 of file HttpRequest.cpp.
{
    return (this->_parsingChunkSize);
}
References _parsingChunkSize.
Referenced by RequestParse::bodyChunked().
methodToString()
const std::string HttpRequest::methodToString (void) const
Converts the HTTP method enum to its string representation.
Definition at line 191 of file HttpRequest.cpp.
{
    switch (this->_method)
    {
        case RequestMethod::GET:
            return "GET";
        case RequestMethod::HEAD:
            return "HEAD";
        case RequestMethod::POST:
            return "POST";
        case RequestMethod::PUT:
            return "PUT";
        case RequestMethod::DELETE:
            return "DELETE";
        case RequestMethod::TRACE:
            return "TRACE";
        case RequestMethod::CONNECT:
            return "CONNECT";
        case RequestMethod::PATCH:
            return "PATCH";
        case RequestMethod::INVALID:
            return "INVALID";
        default:
            return "INVALID";
    }
}
References _method, RequestMethod::CONNECT, RequestMethod::DELETE, RequestMethod::GET, RequestMethod::HEAD, RequestMethod::INVALID, RequestMethod::PATCH, RequestMethod::POST, RequestMethod::PUT, and RequestMethod::TRACE.
Referenced by CgiHandler::buildEnvp().
operator=()
HttpRequest & HttpRequest::operator= (const HttpRequest & rhs) private
removeHeader()
void HttpRequest::removeHeader (const std::string & key)
Removes a header from the request by name.
Definition at line 345 of file HttpRequest.cpp.
{
    std::string lowerKey = toLower(key);
    _headers.erase(lowerKey);
}
References _headers, and toLower().
Referenced by RequestParse::handleRawRequest().
reset()
void HttpRequest::reset (void)
Resets the HttpRequest object to its initial state.
Clears headers, body, buffers, and resets parsing flags.
Definition at line 158 of file HttpRequest.cpp.
{
    this->_method = RequestMethod::INVALID;
    this->_uri.clear();
    this->_major = 0;
    this->_minor = 0;
    this->_headers.clear();
    this->_meta.resetMeta();
    this->_body.clear();
    this->_parseError = ResponseStatus::OK;
    this->_state = RequestState::RequestLine;
    this->_route = RouteType::Error;
    this->_rawRequest.clear();
    this->_buffer.clear();
    this->_chunkBuffer.clear();
    this->_currentChunkSize = 0;
    this->_parsingChunkSize = false;
    this->_expectingChunkSeparator = false;
    this->_resolvedPath.clear();
    Logger::instance().log(DEBUG, "HttpRequest::reset complete");
}
References _body, _buffer, _chunkBuffer, _currentChunkSize, _expectingChunkSeparator, _headers, _major, _meta, _method, _minor, _parseError, _parsingChunkSize, _rawRequest, _resolvedPath, _route, _state, _uri, DEBUG, RouteType::Error, Logger::instance(), RequestMethod::INVALID, Logger::log(), ResponseStatus::OK, RequestState::RequestLine, and RequestMeta::resetMeta().
Referenced by Dispatcher::dispatch().
setCurrentChunkSize()
void HttpRequest::setCurrentChunkSize (int size)
Updates the size of the current chunk being parsed.
Definition at line 130 of file HttpRequest.cpp.
{
    this->_currentChunkSize = size;
}
References _currentChunkSize.
Referenced by RequestParse::bodyChunked(), and HttpRequest().
setExpectingChunkSeparator()
void HttpRequest::setExpectingChunkSeparator (bool value)
Definition at line 140 of file HttpRequest.cpp.
{
    this->_expectingChunkSeparator = value;
}
References _expectingChunkSeparator.
Referenced by RequestParse::bodyChunked(), and HttpRequest().
setMajor()
void HttpRequest::setMajor (int major)
Sets the HTTP major version number.
Definition at line 48 of file HttpRequest.cpp.
{ this->_major = major; }
References _major.
Referenced by RequestParse::requestLine().
setMethod()
void HttpRequest::setMethod (const RequestMethod::Method & method)
Sets the HTTP request method.
Definition at line 30 of file HttpRequest.cpp.
{
    this->_method = method;
}
References _method.
Referenced by HttpRequest(), and RequestParse::method().
setMinor()
void HttpRequest::setMinor (int minor)
Sets the HTTP minor version number.
Definition at line 53 of file HttpRequest.cpp.
{ this->_minor = minor; }
References _minor.
Referenced by RequestParse::requestLine().
setParseError()
void HttpRequest::setParseError (ResponseStatus::code reason)
Definition at line 88 of file HttpRequest.cpp.
{
    this->_parseError = reason;
}
References _parseError.
Referenced by RequestParse::bodyChunked(), RequestParse::checkMethod(), RequestParse::handleRawRequest(), RequestParse::headers(), HttpRequest(), RequestParse::method(), RequestParse::requestLine(), and RequestParse::uri().
setParsingChunkSize()
void HttpRequest::setParsingChunkSize (bool value)
Definition at line 135 of file HttpRequest.cpp.
{
    this->_parsingChunkSize = value;
}
References _parsingChunkSize.
Referenced by RequestParse::bodyChunked(), and HttpRequest().
setQueryString()
void HttpRequest::setQueryString (const std::string queryString)
Sets the query string extracted from the URI.
Definition at line 43 of file HttpRequest.cpp.
{ this->_queryString = queryString; }
References _queryString.
Referenced by RequestParse::uri().
setRequestState()
void HttpRequest::setRequestState (RequestState::state state)
Definition at line 93 of file HttpRequest.cpp.
{
    this->_state = state;
}
References _state.
Referenced by RequestParse::body(), RequestParse::bodyChunked(), RequestParse::handleRawRequest(), RequestParse::headers(), HttpRequest(), and RequestParse::uri().
setResolvedPath()
void HttpRequest::setResolvedPath (const std::string path)
Sets the absolute filesystem path resolved from the URI.
Definition at line 148 of file HttpRequest.cpp.
{
    this->_resolvedPath = path;
}
References _resolvedPath.
Referenced by Router::computeResolvedPath(), and Router::isStaticFile().
setRouteType()
void HttpRequest::setRouteType (RouteType::route route)
Definition at line 98 of file HttpRequest.cpp.
{
    this->_route = route;
}
References _route.
Referenced by Router::checkErrorStatus(), Router::isUpload(), and Router::resolve().
setUri()
void HttpRequest::setUri (const std::string & uri)
Sets the request target URI.
Definition at line 38 of file HttpRequest.cpp.
{ this->_uri = uri; }
References _uri.
Referenced by RequestParse::uri().
Member Data Documentation
_body
std::string HttpRequest::_body private
Definition at line 29 of file HttpRequest.hpp.
Referenced by appendBody(), appendBody(), getBody(), and reset().
_buffer
std::string HttpRequest::_buffer private
Definition at line 34 of file HttpRequest.hpp.
Referenced by clearBuffer(), getBuffer(), and reset().
_chunkBuffer
std::string HttpRequest::_chunkBuffer private
Definition at line 35 of file HttpRequest.hpp.
Referenced by clearChunkBuffer(), getChunkBuffer(), and reset().
_currentChunkSize
int HttpRequest::_currentChunkSize private
Definition at line 36 of file HttpRequest.hpp.
Referenced by getCurrentChunkSize(), reset(), and setCurrentChunkSize().
_expectingChunkSeparator
bool HttpRequest::_expectingChunkSeparator private
Definition at line 38 of file HttpRequest.hpp.
Referenced by isExpectingChunkSeparator(), reset(), and setExpectingChunkSeparator().
_headers
std::map<std::string, std::string> HttpRequest::_headers private
Definition at line 27 of file HttpRequest.hpp.
Referenced by addHeader(), getAllHeaders(), getHeader(), hasHeader(), removeHeader(), and reset().
_major
int HttpRequest::_major private
Definition at line 25 of file HttpRequest.hpp.
Referenced by getHttpVersion(), reset(), and setMajor().
_meta
RequestMeta HttpRequest::_meta private
Definition at line 28 of file HttpRequest.hpp.
Referenced by getMeta(), getMeta(), and reset().
_method
RequestMethod::Method HttpRequest::_method private
Definition at line 22 of file HttpRequest.hpp.
Referenced by getMethod(), methodToString(), reset(), and setMethod().
_minor
int HttpRequest::_minor private
Definition at line 26 of file HttpRequest.hpp.
Referenced by getHttpVersion(), reset(), and setMinor().
_parseError
ResponseStatus::code HttpRequest::_parseError private
Definition at line 30 of file HttpRequest.hpp.
Referenced by getParseError(), reset(), and setParseError().
_parsingChunkSize
bool HttpRequest::_parsingChunkSize private
Definition at line 37 of file HttpRequest.hpp.
Referenced by isParsingChunkSize(), reset(), and setParsingChunkSize().
_queryString
std::string HttpRequest::_queryString private
Definition at line 24 of file HttpRequest.hpp.
Referenced by getQueryString(), and setQueryString().
_rawRequest
std::string HttpRequest::_rawRequest private
Definition at line 33 of file HttpRequest.hpp.
Referenced by appendRaw(), getRaw(), and reset().
_resolvedPath
std::string HttpRequest::_resolvedPath private
Definition at line 39 of file HttpRequest.hpp.
Referenced by getResolvedPath(), reset(), and setResolvedPath().
_route
RouteType::route HttpRequest::_route private
Definition at line 32 of file HttpRequest.hpp.
Referenced by getRouteType(), reset(), and setRouteType().
_state
RequestState::state HttpRequest::_state private
Definition at line 31 of file HttpRequest.hpp.
Referenced by getState(), reset(), and setRequestState().
_uri
std::string HttpRequest::_uri private
Definition at line 23 of file HttpRequest.hpp.
Referenced by getUri(), reset(), and setUri().
The documentation for this class was generated from the following files:
request/HttpRequest.hpp
request/HttpRequest.cpp