Webservinho: ClientConnection Class Reference
ClientConnection Class Reference
#include <init/ClientConnection.hpp>
Public Member Functions
void adoptFD (int fd)
Associates a socket FD with this client, closing any previous one.
std::string & cgiBuffer ()
void clearBuffer (void)
Clears the pending request buffer.
void clearCgi ()
Resets all CGI-related state (after process termination).
ClientConnection (ClientConnection const &src)
Copy constructor — duplicates configuration but not socket state.
ClientConnection (ServerConfig const &config)
Constructs a new ClientConnection with default state.
bool completedRequest (void)
Checks if the current HTTP request has been fully received and parsed.
int getCgiFd () const
pid_t getCgiPid () const
std::time_t getCgiStart () const
int const & getFD (void) const
bool getKeepAlive (void) const
HttpRequest & getRequest (void)
std::string const & getRequestBuffer (void) const
HttpResponse & getResponse (void)
std::string const & getResponseBuffer (void) const
size_t const & getSentBytes (void) const
ServerConfig const & getServerConfig (void) const
bool hasCgi () const
Returns whether a CGI process is currently associated with this client.
bool isCgiActive () const
Alias for hasCgi(), kept for backward compatibility.
ssize_t recvData (void)
Receives incoming data from the client socket.
ssize_t sendData (ClientConnection &client, size_t sent, size_t toSend)
Sends response data to the client.
void setCgiActive (bool v)
void setCgiFd (int fd)
void setCgiPid (pid_t pid)
void setCgiStart (std::time_t t)
void setKeepAlive (bool keepAlive)
void setResponseBuffer (const std::string &buffer)
void setSentBytes (size_t bytes)
~ClientConnection (void)
Destructor — closes the client socket if still open.
Private Member Functions
ClientConnection & operator= (ClientConnection const &rhs)
Private Attributes
std::string _cgiBuffer
int _cgiFd
pid_t _cgiPid
std::time_t _cgiStart
int _fd
bool _hasCgi
HttpRequest _httpRequest
HttpResponse _httpResponse
bool _keepAlive
std::string _requestBuffer
std::string _responseBuffer
size_t _sentBytes
ServerConfig const & _serverConfig
Detailed Description
Definition at line 14 of file ClientConnection.hpp.
Constructor & Destructor Documentation
ClientConnection() [1/2]
ClientConnection::ClientConnection (ServerConfig const & config)
Constructs a new ClientConnection with default state.
Parameters
config Server configuration associated with this client.
Definition at line 31 of file ClientConnection.cpp.
    : _fd(-1), _serverConfig(config), _sentBytes(0), _keepAlive(true),
      _hasCgi(false), _cgiFd(-1), _cgiPid(-1), _cgiStart(0)
{
    Logger::instance().log(DEBUG, "ClientConnection: created with default state");
}
References DEBUG, Logger::instance(), and Logger::log().
ClientConnection() [2/2]
ClientConnection::ClientConnection (ClientConnection const & src)
Copy constructor — duplicates configuration but not socket state.
Definition at line 41 of file ClientConnection.cpp.
    : _fd(-1), _serverConfig(src._serverConfig), _sentBytes(0), _keepAlive(src._keepAlive),
      _hasCgi(false), _cgiFd(-1), _cgiPid(-1), _cgiStart(0)
{
    Logger::instance().log(DEBUG, "ClientConnection: copy-constructed");
}
References DEBUG, Logger::instance(), and Logger::log().
~ClientConnection()
ClientConnection::~ClientConnection (void)
Destructor — closes the client socket if still open.
Definition at line 17 of file ClientConnection.cpp.
{
    if (this->_fd != -1)
    {
        ::close(this->_fd);
        Logger::instance().log(DEBUG, "ClientConnection: closed FD -> " + toString(_fd));
    }
}
References _fd, DEBUG, Logger::instance(), Logger::log(), and toString().
Member Function Documentation
adoptFD()
void ClientConnection::adoptFD (int fd)
Associates a socket FD with this client, closing any previous one.
Definition at line 51 of file ClientConnection.cpp.
{
    if (_fd >= 0)
    {
        Logger::instance().log(WARNING, "ClientConnection: closing previous FD -> " + toString(_fd));
        ::close(_fd);
    }
    _fd = fd;
    Logger::instance().log(DEBUG, "ClientConnection: adopted new FD -> " + toString(_fd));
}
References _fd, DEBUG, Logger::instance(), Logger::log(), toString(), and WARNING.
Referenced by WebServer::queueClientConnections().
cgiBuffer()
std::string & ClientConnection::cgiBuffer ()
Definition at line 197 of file ClientConnection.cpp.
{ return (_cgiBuffer); }
References _cgiBuffer.
Referenced by Dispatcher::dispatch(), and WebServer::handleCgiReadable().
clearBuffer()
void ClientConnection::clearBuffer (void)
Clears the pending request buffer.
Definition at line 151 of file ClientConnection.cpp.
{
    _requestBuffer.clear();
    Logger::instance().log(DEBUG, "ClientConnection::clearBuffer() called");
}
References _requestBuffer, DEBUG, Logger::instance(), and Logger::log().
Referenced by WebServer::sendResponse().
clearCgi()
void ClientConnection::clearCgi ()
Resets all CGI-related state (after process termination).
Definition at line 210 of file ClientConnection.cpp.
{
    _hasCgi = false;
    _cgiFd = -1;
    _cgiPid = -1;
    _cgiStart = 0;
    _cgiBuffer.clear();
}
References _cgiBuffer, _cgiFd, _cgiPid, _cgiStart, and _hasCgi.
Referenced by WebServer::handleCgiReadable(), WebServer::runServer(), and WebServer::sweepCgiTimeouts().
completedRequest()
bool ClientConnection::completedRequest (void)
Checks if the current HTTP request has been fully received and parsed.
Definition at line 135 of file ClientConnection.cpp.
{
    if (_httpRequest.getState() == RequestState::Complete)
    {
        Logger::instance().log(DEBUG, "ClientConnection::completedRequest -> TRUE");
        Logger::instance().log(DEBUG, "ParseError code -> " + toString(_httpRequest.getParseError()));
        return (true);
    }
    Logger::instance().log(DEBUG, "ClientConnection::completedRequest -> FALSE (state = " +
        toString(_httpRequest.getState()) + ")");
    return (false);
}
References _httpRequest, RequestState::Complete, DEBUG, HttpRequest::getParseError(), HttpRequest::getState(), Logger::instance(), Logger::log(), and toString().
Referenced by WebServer::receiveRequest().
getCgiFd()
int ClientConnection::getCgiFd () const
Definition at line 191 of file ClientConnection.cpp.
{ return (_cgiFd); }
References _cgiFd.
Referenced by WebServer::receiveRequest().
getCgiPid()
pid_t ClientConnection::getCgiPid () const
Definition at line 193 of file ClientConnection.cpp.
{ return (_cgiPid); }
References _cgiPid.
Referenced by WebServer::handleCgiReadable(), and WebServer::sweepCgiTimeouts().
getCgiStart()
std::time_t ClientConnection::getCgiStart () const
Definition at line 195 of file ClientConnection.cpp.
{ return (_cgiStart); }
References _cgiStart.
Referenced by WebServer::sweepCgiTimeouts().
getFD()
int const & ClientConnection::getFD (void) const
Definition at line 157 of file ClientConnection.cpp.
{ return (this->_fd); }
References _fd.
Referenced by Dispatcher::dispatch(), WebServer::receiveRequest(), sendData(), and WebServer::sendResponse().
getKeepAlive()
bool ClientConnection::getKeepAlive (void) const
Definition at line 171 of file ClientConnection.cpp.
{ return (this->_keepAlive); }
References _keepAlive.
Referenced by WebServer::sendResponse().
getRequest()
HttpRequest & ClientConnection::getRequest (void)
Definition at line 175 of file ClientConnection.cpp.
{ return (this->_httpRequest); }
References _httpRequest.
Referenced by Dispatcher::dispatch(), WebServer::handleCgiReadable(), WebServer::receiveRequest(), WebServer::runServer(), and WebServer::sweepCgiTimeouts().
getRequestBuffer()
std::string const & ClientConnection::getRequestBuffer (void) const
Definition at line 161 of file ClientConnection.cpp.
{ return (_requestBuffer); }
References _requestBuffer.
getResponse()
HttpResponse & ClientConnection::getResponse (void)
Definition at line 177 of file ClientConnection.cpp.
{ return (this->_httpResponse); }
References _httpResponse.
Referenced by Dispatcher::dispatch(), WebServer::handleCgiReadable(), WebServer::runServer(), and WebServer::sweepCgiTimeouts().
getResponseBuffer()
std::string const & ClientConnection::getResponseBuffer (void) const
Definition at line 163 of file ClientConnection.cpp.
{ return (_responseBuffer); }
References _responseBuffer.
Referenced by Dispatcher::dispatch(), sendData(), and WebServer::sendResponse().
getSentBytes()
size_t const & ClientConnection::getSentBytes (void) const
Definition at line 159 of file ClientConnection.cpp.
{ return (this->_sentBytes); }
References _sentBytes.
Referenced by WebServer::sendResponse().
getServerConfig()
ServerConfig const & ClientConnection::getServerConfig (void) const
Definition at line 165 of file ClientConnection.cpp.
{ return (this->_serverConfig); }
References _serverConfig.
Referenced by ResponseBuilder::build(), Dispatcher::dispatch(), and recvData().
hasCgi()
bool ClientConnection::hasCgi () const
Returns whether a CGI process is currently associated with this client.
Definition at line 184 of file ClientConnection.cpp.
{ return (_hasCgi); }
References _hasCgi.
Referenced by Dispatcher::dispatch(), and WebServer::receiveRequest().
isCgiActive()
bool ClientConnection::isCgiActive () const
Alias for hasCgi(), kept for backward compatibility.
Definition at line 189 of file ClientConnection.cpp.
{ return (_hasCgi); }
References _hasCgi.
operator=()
ClientConnection & ClientConnection::operator= (ClientConnection const & rhs) private
recvData()
ssize_t ClientConnection::recvData (void)
Receives incoming data from the client socket.
Reads from the socket into an internal request buffer, and delegates parsing to RequestParse. Throws on I/O error.
Returns
Number of bytes received, or 0 on EOF.
Definition at line 70 of file ClientConnection.cpp.
{
    if (_fd == -1)
        throw std::runtime_error("ClientConnection::recvData -> invalid FD (-1)");
    char buffer[4096];
    ssize_t bytesRecv = ::recv(this->_fd, buffer, sizeof(buffer), 0);
    Logger::instance().log(DEBUG, "ClientConnection::recvData bytesRecv = " + toString(bytesRecv));
    if (bytesRecv == -1)
        throw std::runtime_error("recvData: read failure");
    if (bytesRecv == 0)
    {
        Logger::instance().log(INFO, "ClientConnection::recvData EOF reached");
        return (0);
    }
    _requestBuffer.append(buffer, bytesRecv);
    Logger::instance().log(DEBUG,
        "ClientConnection::recvData appended " + toString(bytesRecv) +
        " bytes (total buffer size: " + toString(_requestBuffer.size()) + ")");
    RequestParse::handleRawRequest(_requestBuffer, _httpRequest, this->getServerConfig());
    Logger::instance().log(DEBUG, "ClientConnection::recvData processed request data");
    _requestBuffer.clear();
    return (bytesRecv);
}
References _fd, _httpRequest, _requestBuffer, DEBUG, getServerConfig(), RequestParse::handleRawRequest(), INFO, Logger::instance(), Logger::log(), and toString().
Referenced by WebServer::receiveRequest().
sendData()
ssize_t ClientConnection::sendData (ClientConnection & client, size_t sent, size_t toSend)
Sends response data to the client.
Parameters
client Target connection.
sent Number of bytes already sent.
toSend Maximum number of bytes to send.
Returns
Number of bytes successfully sent.
Exceptions
std::runtime_error on send failure.
Definition at line 110 of file ClientConnection.cpp.
{
    if (_fd == -1)
        throw std::runtime_error("ClientConnection::sendData -> invalid FD (-1)");
    const std::string& response = client.getResponseBuffer();
    const char* response_string = response.c_str() + sent;
    ssize_t bytesSent = ::send(client.getFD(), response_string, toSend, MSG_NOSIGNAL);
    if (bytesSent == -1)
        throw std::runtime_error("sendData: send failure");
    if (bytesSent == 0)
    {
        Logger::instance().log(WARNING, "ClientConnection::sendData returned 0 (client closed connection?)");
        return (0);
    }
    Logger::instance().log(DEBUG, "ClientConnection::sendData sent " + toString(bytesSent) + " bytes");
    return (bytesSent);
}
References _fd, DEBUG, getFD(), getResponseBuffer(), Logger::instance(), Logger::log(), toString(), and WARNING.
Referenced by WebServer::sendResponse().
setCgiActive()
void ClientConnection::setCgiActive (bool v)
Definition at line 199 of file ClientConnection.cpp.
{ _hasCgi = v; }
References _hasCgi.
Referenced by Dispatcher::dispatch().
setCgiFd()
void ClientConnection::setCgiFd (int fd)
Definition at line 201 of file ClientConnection.cpp.
{ _cgiFd = fd; }
References _cgiFd.
Referenced by Dispatcher::dispatch().
setCgiPid()
void ClientConnection::setCgiPid (pid_t pid)
Definition at line 203 of file ClientConnection.cpp.
{ _cgiPid = pid; }
References _cgiPid.
Referenced by Dispatcher::dispatch().
setCgiStart()
void ClientConnection::setCgiStart (std::time_t t)
Definition at line 205 of file ClientConnection.cpp.
{ _cgiStart = t; }
References _cgiStart.
Referenced by Dispatcher::dispatch().
setKeepAlive()
void ClientConnection::setKeepAlive (bool keepAlive)
Definition at line 173 of file ClientConnection.cpp.
{ this->_keepAlive = keepAlive; }
References _keepAlive.
Referenced by Dispatcher::dispatch().
setResponseBuffer()
void ClientConnection::setResponseBuffer (const std::string & buffer)
Definition at line 169 of file ClientConnection.cpp.
{ this->_responseBuffer = buffer; }
References _responseBuffer.
Referenced by Dispatcher::dispatch(), WebServer::handleCgiReadable(), WebServer::receiveRequest(), WebServer::runServer(), and WebServer::sweepCgiTimeouts().
setSentBytes()
void ClientConnection::setSentBytes (size_t bytes)
Definition at line 167 of file ClientConnection.cpp.
{ this->_sentBytes = bytes; }
References _sentBytes.
Referenced by WebServer::receiveRequest(), and WebServer::sendResponse().
Member Data Documentation
_cgiBuffer
std::string ClientConnection::_cgiBuffer private
Definition at line 31 of file ClientConnection.hpp.
Referenced by cgiBuffer(), and clearCgi().
_cgiFd
int ClientConnection::_cgiFd private
Definition at line 28 of file ClientConnection.hpp.
Referenced by clearCgi(), getCgiFd(), and setCgiFd().
_cgiPid
pid_t ClientConnection::_cgiPid private
Definition at line 29 of file ClientConnection.hpp.
Referenced by clearCgi(), getCgiPid(), and setCgiPid().
_cgiStart
std::time_t ClientConnection::_cgiStart private
Definition at line 30 of file ClientConnection.hpp.
Referenced by clearCgi(), getCgiStart(), and setCgiStart().
_fd
int ClientConnection::_fd private
Definition at line 17 of file ClientConnection.hpp.
Referenced by adoptFD(), getFD(), recvData(), sendData(), and ~ClientConnection().
_hasCgi
bool ClientConnection::_hasCgi private
Definition at line 27 of file ClientConnection.hpp.
Referenced by clearCgi(), hasCgi(), isCgiActive(), and setCgiActive().
_httpRequest
HttpRequest ClientConnection::_httpRequest private
Definition at line 23 of file ClientConnection.hpp.
Referenced by completedRequest(), getRequest(), and recvData().
_httpResponse
HttpResponse ClientConnection::_httpResponse private
Definition at line 24 of file ClientConnection.hpp.
Referenced by getResponse().
_keepAlive
bool ClientConnection::_keepAlive private
Definition at line 22 of file ClientConnection.hpp.
Referenced by getKeepAlive(), and setKeepAlive().
_requestBuffer
std::string ClientConnection::_requestBuffer private
Definition at line 19 of file ClientConnection.hpp.
Referenced by clearBuffer(), getRequestBuffer(), and recvData().
_responseBuffer
std::string ClientConnection::_responseBuffer private
Definition at line 20 of file ClientConnection.hpp.
Referenced by getResponseBuffer(), and setResponseBuffer().
_sentBytes
size_t ClientConnection::_sentBytes private
Definition at line 21 of file ClientConnection.hpp.
Referenced by getSentBytes(), and setSentBytes().
_serverConfig
ServerConfig const& ClientConnection::_serverConfig private
Definition at line 18 of file ClientConnection.hpp.
Referenced by getServerConfig().
The documentation for this class was generated from the following files:
init/ClientConnection.hpp
init/ClientConnection.cpp