Webservinho: LocationConfig Class Reference
LocationConfig Class Reference
#include <config/LocationConfig.hpp>
Public Member Functions
void addCgiExtension (std::string const &, std::string const &)
Adds an extension-handler pair for CGI execution.
bool getAutoindex (void) const
std::map< std::string, std::string > const & getCgiExtension (void) const
std::string const & getCgiPath (void) const
bool getHasAutoIndex (void) const
bool getHasIndexFiles (void) const
bool getHasRoot (void) const
std::string const & getIndex (void) const
std::vector< RequestMethod::Method > const & getMethods (void) const
std::string const & getPath (void) const
std::pair< int, std::string > const & getReturn (void) const
std::string const & getRoot (void) const
bool getUploadEnabled (void) const
std::string const & getUploadPath (void) const
LocationConfig (LocationConfig const &src)
Copy constructor — clones all configuration attributes.
LocationConfig (std::string newPath)
Constructs a new LocationConfig for a given path.
void setAutoindex (bool)
Enables or disables directory listing (autoindex).
void setCgiPath (std::string)
Sets the path to the CGI executable.
void setIndex (std::string)
Defines the default index file for this location.
void setMethods (std::vector< RequestMethod::Method >)
Sets the list of allowed HTTP methods.
void setReturn (std::pair< int, std::string >)
Sets the HTTP redirection rule (status, URL).
void setRoot (std::string)
Sets the root directory for this location.
void setUploadEnabled (bool)
Enables or disables file upload for this location.
void setUploadPath (std::string)
Defines the upload directory for incoming files.
~LocationConfig (void)
Destructor — no dynamic resources to release.
Private Member Functions
LocationConfig & operator= (LocationConfig const &rhs)
Private Attributes
bool _autoindex
std::map< std::string, std::string > _cgiExtension
std::string _cgiPath
bool _hasAutoIndex
bool _hasIndexFiles
bool _hasRoot
std::string _indexFiles
std::vector< RequestMethod::Method > _methods
std::string _path
std::pair< int, std::string > _return
std::string _root
bool _uploadEnabled
std::string _uploadPath
Detailed Description
Definition at line 11 of file LocationConfig.hpp.
Constructor & Destructor Documentation
LocationConfig() [1/2]
LocationConfig::LocationConfig (std::string newPath)
Constructs a new LocationConfig for a given path.
Initializes defaults:
autoindex disabled
uploads disabled
default allowed method: GET
Definition at line 12 of file LocationConfig.cpp.
    : _path(newPath),
    _autoindex(false),
    _uploadEnabled(false),
    _hasRoot(false),
    _hasIndexFiles(false),
    _hasAutoIndex(false)
{
    this->_methods.push_back(RequestMethod::GET);
}
References _methods, and RequestMethod::GET.
LocationConfig() [2/2]
LocationConfig::LocationConfig (LocationConfig const & src)
Copy constructor — clones all configuration attributes.
Definition at line 26 of file LocationConfig.cpp.
    : _path(src._path),
    _root(src._root),
    _indexFiles(src._indexFiles),
    _autoindex(src._autoindex),
    _methods(src._methods),
    _return(src._return),
    _uploadPath(src._uploadPath),
    _uploadEnabled(src._uploadEnabled),
    _cgiPath(src._cgiPath),
    _cgiExtension(src._cgiExtension),
    _hasRoot(src._hasRoot),
    _hasIndexFiles(src._hasIndexFiles),
    _hasAutoIndex(src._hasAutoIndex)
{}
~LocationConfig()
LocationConfig::~LocationConfig (void)
Destructor — no dynamic resources to release.
Definition at line 45 of file LocationConfig.cpp.
{}
Member Function Documentation
addCgiExtension()
void LocationConfig::addCgiExtension (std::string const & ext, std::string const & handler)
Adds an extension-handler pair for CGI execution.
Example: addCgiExtension(".py", "/usr/bin/python3");
Definition at line 184 of file LocationConfig.cpp.
{
    this->_cgiExtension[ext] = handler;
}
References _cgiExtension.
Referenced by ConfigParser::parseLocationBlock().
getAutoindex()
bool LocationConfig::getAutoindex (void) const
Returns
True if directory autoindexing is enabled.
Definition at line 65 of file LocationConfig.cpp.
{ return this->_autoindex; }
References _autoindex.
Referenced by Router::isAutoIndex().
getCgiExtension()
std::map< std::string, std::string > const & LocationConfig::getCgiExtension (void) const
Returns
Map of CGI file extensions and their associated interpreters.
Definition at line 95 of file LocationConfig.cpp.
{ return this->_cgiExtension; }
References _cgiExtension.
Referenced by Router::hasCgiExtension().
getCgiPath()
std::string const & LocationConfig::getCgiPath (void) const
Returns
Path to the CGI executable handler.
Definition at line 90 of file LocationConfig.cpp.
{ return this->_cgiPath; }
References _cgiPath.
Referenced by Router::computeResolvedPath(), Router::isCgi(), and Router::resolve().
getHasAutoIndex()
bool LocationConfig::getHasAutoIndex (void) const
Returns
True if autoindex directive was explicitly set.
Definition at line 110 of file LocationConfig.cpp.
{ return this->_hasAutoIndex; }
References _hasAutoIndex.
Referenced by Router::isAutoIndex(), and ConfigParser::parseLocationBlock().
getHasIndexFiles()
bool LocationConfig::getHasIndexFiles (void) const
Returns
True if an index file is explicitly set.
Definition at line 105 of file LocationConfig.cpp.
{ return this->_hasIndexFiles; }
References _hasIndexFiles.
Referenced by Router::computeResolvedPath(), ConfigParser::parseLocationBlock(), and Router::resolve().
getHasRoot()
bool LocationConfig::getHasRoot (void) const
Returns
True if a root directive is explicitly set.
Definition at line 100 of file LocationConfig.cpp.
{ return this->_hasRoot; }
References _hasRoot.
Referenced by Router::computeResolvedPath(), ConfigParser::parseLocationBlock(), and Router::resolve().
getIndex()
std::string const & LocationConfig::getIndex (void) const
Returns
The index file (e.g., "index.html").
Definition at line 60 of file LocationConfig.cpp.
{ return this->_indexFiles; }
References _indexFiles.
Referenced by Router::computeResolvedPath(), and Router::resolve().
getMethods()
std::vector< RequestMethod::Method > const & LocationConfig::getMethods (void) const
Returns
The list of allowed HTTP methods (GET, POST, DELETE).
Definition at line 70 of file LocationConfig.cpp.
{ return this->_methods; }
References _methods.
Referenced by RequestParse::checkMethod().
getPath()
std::string const & LocationConfig::getPath (void) const
Returns
The route path pattern of the location block.
Definition at line 50 of file LocationConfig.cpp.
{ return this->_path; }
References _path.
Referenced by Router::computeResolvedPath(), Router::isUpload(), and ServerConfig::matchLocation().
getReturn()
std::pair< int, std::string > const & LocationConfig::getReturn (void) const
Returns
HTTP redirect rule as (status_code, target_url).
Definition at line 75 of file LocationConfig.cpp.
{ return this->_return; }
References _return.
Referenced by Router::isRedirect().
getRoot()
std::string const & LocationConfig::getRoot (void) const
Returns
The root directory assigned to this location.
Definition at line 55 of file LocationConfig.cpp.
{ return this->_root; }
References _root.
Referenced by Router::computeResolvedPath(), and Router::resolve().
getUploadEnabled()
bool LocationConfig::getUploadEnabled (void) const
Returns
True if uploads are enabled for this location.
Definition at line 85 of file LocationConfig.cpp.
{ return this->_uploadEnabled; }
References _uploadEnabled.
Referenced by Router::isUpload().
getUploadPath()
std::string const & LocationConfig::getUploadPath (void) const
Returns
Directory path where uploaded files will be stored.
Definition at line 80 of file LocationConfig.cpp.
{ return this->_uploadPath; }
References _uploadPath.
Referenced by Dispatcher::dispatch(), and Router::isUpload().
operator=()
LocationConfig & LocationConfig::operator= (LocationConfig const & rhs) private
setAutoindex()
void LocationConfig::setAutoindex (bool newAutoindex)
Enables or disables directory listing (autoindex).
Definition at line 133 of file LocationConfig.cpp.
{
    this->_autoindex = newAutoindex;
    this->_hasAutoIndex = true;
}
References _autoindex, and _hasAutoIndex.
Referenced by ConfigParser::parseLocationBlock().
setCgiPath()
void LocationConfig::setCgiPath (std::string newPath)
Sets the path to the CGI executable.
Definition at line 174 of file LocationConfig.cpp.
{
    this->_cgiPath = newPath;
}
References _cgiPath.
Referenced by ConfigParser::parseLocationBlock().
setIndex()
void LocationConfig::setIndex (std::string newIndex)
Defines the default index file for this location.
Definition at line 124 of file LocationConfig.cpp.
{
    this->_indexFiles = newIndex;
    this->_hasIndexFiles = true;
}
References _hasIndexFiles, and _indexFiles.
Referenced by ConfigParser::parseLocationBlock().
setMethods()
void LocationConfig::setMethods (std::vector< RequestMethod::Method > newMethods)
Sets the list of allowed HTTP methods.
Definition at line 142 of file LocationConfig.cpp.
{
    this->_methods = newMethods;
}
References _methods.
Referenced by ConfigParser::parseLocationBlock().
setReturn()
void LocationConfig::setReturn (std::pair< int, std::string > newReturn)
Sets the HTTP redirection rule (status, URL).
Definition at line 150 of file LocationConfig.cpp.
{
    this->_return = newReturn;
}
References _return.
Referenced by ConfigParser::parseLocationBlock().
setRoot()
void LocationConfig::setRoot (std::string newRoot)
Sets the root directory for this location.
Definition at line 115 of file LocationConfig.cpp.
{
    this->_root = newRoot;
    this->_hasRoot = true;
}
References _hasRoot, and _root.
Referenced by ConfigParser::parseLocationBlock().
setUploadEnabled()
void LocationConfig::setUploadEnabled (bool enabled)
Enables or disables file upload for this location.
Definition at line 166 of file LocationConfig.cpp.
{
    this->_uploadEnabled = enabled;
}
References _uploadEnabled.
Referenced by ConfigParser::parseLocationBlock().
setUploadPath()
void LocationConfig::setUploadPath (std::string newPath)
Defines the upload directory for incoming files.
Definition at line 158 of file LocationConfig.cpp.
{
    this->_uploadPath = newPath;
}
References _uploadPath.
Referenced by ConfigParser::parseLocationBlock().
Member Data Documentation
_autoindex
bool LocationConfig::_autoindex private
Definition at line 18 of file LocationConfig.hpp.
Referenced by getAutoindex(), and setAutoindex().
_cgiExtension
std::map<std::string, std::string> LocationConfig::_cgiExtension private
Definition at line 26 of file LocationConfig.hpp.
Referenced by addCgiExtension(), and getCgiExtension().
_cgiPath
std::string LocationConfig::_cgiPath private
Definition at line 25 of file LocationConfig.hpp.
Referenced by getCgiPath(), and setCgiPath().
_hasAutoIndex
bool LocationConfig::_hasAutoIndex private
Definition at line 31 of file LocationConfig.hpp.
Referenced by getHasAutoIndex(), and setAutoindex().
_hasIndexFiles
bool LocationConfig::_hasIndexFiles private
Definition at line 30 of file LocationConfig.hpp.
Referenced by getHasIndexFiles(), and setIndex().
_hasRoot
bool LocationConfig::_hasRoot private
Definition at line 29 of file LocationConfig.hpp.
Referenced by getHasRoot(), and setRoot().
_indexFiles
std::string LocationConfig::_indexFiles private
Definition at line 17 of file LocationConfig.hpp.
Referenced by getIndex(), and setIndex().
_methods
std::vector<RequestMethod::Method> LocationConfig::_methods private
Definition at line 19 of file LocationConfig.hpp.
Referenced by getMethods(), LocationConfig(), and setMethods().
_path
std::string LocationConfig::_path private
Definition at line 15 of file LocationConfig.hpp.
Referenced by getPath().
_return
std::pair<int, std::string> LocationConfig::_return private
Definition at line 22 of file LocationConfig.hpp.
Referenced by getReturn(), and setReturn().
_root
std::string LocationConfig::_root private
Definition at line 16 of file LocationConfig.hpp.
Referenced by getRoot(), and setRoot().
_uploadEnabled
bool LocationConfig::_uploadEnabled private
Definition at line 24 of file LocationConfig.hpp.
Referenced by getUploadEnabled(), and setUploadEnabled().
_uploadPath
std::string LocationConfig::_uploadPath private
Definition at line 23 of file LocationConfig.hpp.
Referenced by getUploadPath(), and setUploadPath().
The documentation for this class was generated from the following files:
config/LocationConfig.hpp
config/LocationConfig.cpp