Webservinho: RequestMeta Class Reference
RequestMeta Class Reference
#include <request/RequestMeta.hpp>
Public Member Functions
std::size_t getContentLength (void) const
Returns the Content-Length value.
bool getExpectContinue (void) const
Returns true if the client expects a 100-Continue response.
std::string getHost (void) const
Returns the stored Host header value.
bool isChunked (void) const
Returns true if transfer encoding is chunked.
bool isRedirect (void) const
Returns true if this request corresponds to an HTTP redirect.
RequestMeta ()
Default constructor for RequestMeta.
void resetMeta (void)
Resets all metadata fields to default values.
void setChunked (bool chunked)
Defines whether the request uses chunked transfer encoding.
void setConnectionClose (bool connection_close)
Defines whether the connection should be closed after the response.
void setContentLength (std::size_t content_length)
Sets the Content-Length value for the request.
void setExpectContinue (bool expect_continue)
Sets the Expect: 100-continue flag for the request.
void setHost (const std::string &host)
Stores the value of the Host header for this request.
void setRedirect (bool redirect)
Sets whether this request is associated with a redirect.
bool shouldClose (void) const
Returns true if the connection should be closed.
~RequestMeta ()
Destructor for RequestMeta.
Private Member Functions
RequestMeta & operator= (const RequestMeta &rhs)
RequestMeta (const RequestMeta &rhs)
Private Attributes
bool _chunked
bool _connectionClose
std::size_t _contentLength
bool _expectContinue
std::string _host
bool _isRedirect
Detailed Description
Definition at line 6 of file RequestMeta.hpp.
Constructor & Destructor Documentation
RequestMeta() [1/2]
RequestMeta::RequestMeta (const RequestMeta & rhs) private
RequestMeta() [2/2]
RequestMeta::RequestMeta ()
Default constructor for RequestMeta.
Initializes an empty metadata container for an HTTP request.
Definition at line 8 of file RequestMeta.cpp.
{}
~RequestMeta()
RequestMeta::~RequestMeta ()
Destructor for RequestMeta.
Definition at line 13 of file RequestMeta.cpp.
{}
Member Function Documentation
getContentLength()
std::size_t RequestMeta::getContentLength (void) const
Returns the Content-Length value.
Definition at line 81 of file RequestMeta.cpp.
{ return (this->_contentLength); }
References _contentLength.
Referenced by RequestParse::body(), and RequestParse::handleRawRequest().
getExpectContinue()
bool RequestMeta::getExpectContinue (void) const
Returns true if the client expects a 100-Continue response.
Definition at line 96 of file RequestMeta.cpp.
{ return (this->_expectContinue); }
References _expectContinue.
Referenced by WebServer::receiveRequest().
getHost()
std::string RequestMeta::getHost (void) const
Returns the stored Host header value.
Definition at line 106 of file RequestMeta.cpp.
{ return (this->_host); }
References _host.
isChunked()
bool RequestMeta::isChunked (void) const
Returns true if transfer encoding is chunked.
Definition at line 86 of file RequestMeta.cpp.
{ return (this->_chunked); }
References _chunked.
Referenced by RequestParse::body(), and RequestParse::handleRawRequest().
isRedirect()
bool RequestMeta::isRedirect (void) const
Returns true if this request corresponds to an HTTP redirect.
Definition at line 101 of file RequestMeta.cpp.
{ return (this->_isRedirect); }
References _isRedirect.
operator=()
RequestMeta & RequestMeta::operator= (const RequestMeta & rhs) private
resetMeta()
void RequestMeta::resetMeta (void)
Resets all metadata fields to default values.
Clears flags and stored headers for reuse of the same object.
Definition at line 68 of file RequestMeta.cpp.
{
    this->_contentLength = 0;
    this->_chunked = false;
    this->_connectionClose = false;
    this->_expectContinue = false;
    this->_isRedirect = false;
    this->_host.clear();
}
References _chunked, _connectionClose, _contentLength, _expectContinue, _host, and _isRedirect.
Referenced by HttpRequest::reset().
setChunked()
void RequestMeta::setChunked (bool chunked)
Defines whether the request uses chunked transfer encoding.
Definition at line 26 of file RequestMeta.cpp.
{
    this->_chunked = chunked;
}
References _chunked.
Referenced by RequestParse::handleRawRequest(), RequestParse::headers(), and HttpRequest::HttpRequest().
setConnectionClose()
void RequestMeta::setConnectionClose (bool connection_close)
Defines whether the connection should be closed after the response.
Definition at line 34 of file RequestMeta.cpp.
{
    this->_connectionClose = connection_close;
}
References _connectionClose.
Referenced by ResponseBuilder::build(), RequestParse::headers(), and HttpRequest::HttpRequest().
setContentLength()
void RequestMeta::setContentLength (std::size_t content_length)
Sets the Content-Length value for the request.
Definition at line 18 of file RequestMeta.cpp.
{
    this->_contentLength = content_length;
}
References _contentLength.
Referenced by RequestParse::handleRawRequest(), RequestParse::headers(), and HttpRequest::HttpRequest().
setExpectContinue()
void RequestMeta::setExpectContinue (bool expect_continue)
Sets the Expect: 100-continue flag for the request.
Definition at line 42 of file RequestMeta.cpp.
{
    this->_expectContinue = expect_continue;
}
References _expectContinue.
Referenced by RequestParse::headers(), HttpRequest::HttpRequest(), and WebServer::receiveRequest().
setHost()
void RequestMeta::setHost (const std::string & host)
Stores the value of the Host header for this request.
Definition at line 58 of file RequestMeta.cpp.
{
    this->_host = host;
}
References _host.
Referenced by RequestParse::headers().
setRedirect()
void RequestMeta::setRedirect (bool redirect)
Sets whether this request is associated with a redirect.
Definition at line 50 of file RequestMeta.cpp.
{
    this->_isRedirect = redirect;
}
References _isRedirect.
Referenced by HttpRequest::HttpRequest(), and Router::isRedirect().
shouldClose()
bool RequestMeta::shouldClose (void) const
Returns true if the connection should be closed.
Definition at line 91 of file RequestMeta.cpp.
{ return (this->_connectionClose); }
References _connectionClose.
Referenced by ResponseBuilder::build(), and Dispatcher::dispatch().
Member Data Documentation
_chunked
bool RequestMeta::_chunked private
Definition at line 10 of file RequestMeta.hpp.
Referenced by isChunked(), resetMeta(), and setChunked().
_connectionClose
bool RequestMeta::_connectionClose private
Definition at line 11 of file RequestMeta.hpp.
Referenced by resetMeta(), setConnectionClose(), and shouldClose().
_contentLength
std::size_t RequestMeta::_contentLength private
Definition at line 9 of file RequestMeta.hpp.
Referenced by getContentLength(), resetMeta(), and setContentLength().
_expectContinue
bool RequestMeta::_expectContinue private
Definition at line 12 of file RequestMeta.hpp.
Referenced by getExpectContinue(), resetMeta(), and setExpectContinue().
_host
std::string RequestMeta::_host private
Definition at line 14 of file RequestMeta.hpp.
Referenced by getHost(), resetMeta(), and setHost().
_isRedirect
bool RequestMeta::_isRedirect private
Definition at line 13 of file RequestMeta.hpp.
Referenced by isRedirect(), resetMeta(), and setRedirect().
The documentation for this class was generated from the following files:
request/RequestMeta.hpp
request/RequestMeta.cpp