Webservinho: Config Class Reference
Config Class Reference
#include <config/Config.hpp>
Public Member Functions
void addServer (ServerConfig &server)
Adds a new server configuration to the configuration set.
Config (Config const &src)
Copy constructor — performs a deep copy of server configurations.
Config (void)
Default constructor — initializes an empty configuration container.
std::vector< ServerConfig > const & getServerConfig (void) const
Returns the list of all parsed server configurations.
~Config (void)
Destructor — performs cleanup (no dynamic resources used).
Private Member Functions
Config & operator= (Config const &rhs)
Private Attributes
std::vector< ServerConfig > _servers
Detailed Description
Definition at line 9 of file Config.hpp.
Constructor & Destructor Documentation
Config() [1/2]
Config::Config (void)
Default constructor — initializes an empty configuration container.
Definition at line 6 of file Config.cpp.
{}
Config() [2/2]
Config::Config (Config const & src)
Copy constructor — performs a deep copy of server configurations.
Parameters
src Source configuration to copy.
Definition at line 13 of file Config.cpp.
: _servers(src._servers) {}
~Config()
Config::~Config (void)
Destructor — performs cleanup (no dynamic resources used).
Definition at line 18 of file Config.cpp.
{}
Member Function Documentation
addServer()
void Config::addServer (ServerConfig & server)
Adds a new server configuration to the configuration set.
Parameters
server Reference to a ServerConfig object to append.
Definition at line 37 of file Config.cpp.
{
    this->_servers.push_back(server);
}
References _servers.
Referenced by ConfigParser::parseServerBlock().
getServerConfig()
std::vector< ServerConfig > const & Config::getServerConfig (void) const
Returns the list of all parsed server configurations.
Each entry represents a single server block from the configuration file.
Returns
Constant reference to the internal vector of ServerConfig objects.
Definition at line 27 of file Config.cpp.
{
    return (this->_servers);
}
References _servers.
Referenced by WebServer::queueClientConnections(), and WebServer::startServer().
operator=()
Config & Config::operator= (Config const & rhs) private
Member Data Documentation
_servers
std::vector<ServerConfig> Config::_servers private
Definition at line 12 of file Config.hpp.
Referenced by addServer(), and getServerConfig().
The documentation for this class was generated from the following files:
config/Config.hpp
config/Config.cpp