Webservinho: Logger Class Reference
Logger Class Reference
#include <utils/Logger.hpp>
Public Member Functions
void log (LogLevel level, const std::string &message)
Writes a log entry with timestamp, level, and message.
~Logger ()
Closes the active log file on destruction.
Static Public Member Functions
static Logger & instance ()
Returns the singleton instance of the Logger.
Private Member Functions
const std::string levelToString (LogLevel level) const
Converts a LogLevel enum value to its string label.
Logger ()
Initializes the Logger and opens a daily log file.
Private Attributes
std::ofstream _logFile
Detailed Description
Definition at line 22 of file Logger.hpp.
Constructor & Destructor Documentation
Logger()
Logger::Logger () private
Initializes the Logger and opens a daily log file.
Creates (or appends to) a log file named as: ./logs/webserv_YYYY-MM-DD.log
Definition at line 9 of file Logger.cpp.
{
    std::time_t now = time(0);
    tm* timeinfo = localtime(&now);
    char timestamp[20];
    std::strftime(timestamp, sizeof(timestamp), "%Y-%m-%d", timeinfo);
    std::string filename = "./logs/webserv_";
    filename += timestamp;
    filename += ".log";
    _logFile.open(filename.c_str(), std::ios::app);
    if (!_logFile.is_open())
    {
        std::cerr << "Error opening log file." << std::endl;
    }
}
References _logFile.
~Logger()
Logger::~Logger ()
Closes the active log file on destruction.
Definition at line 30 of file Logger.cpp.
{ _logFile.close(); }
References _logFile.
Member Function Documentation
instance()
Logger & Logger::instance () static
Returns the singleton instance of the Logger.
Ensures that only one instance of Logger exists throughout execution.
Definition at line 37 of file Logger.cpp.
{
    static Logger logger;
    return (logger);
}
Referenced by ServerSocket::acceptConnections(), ClientConnection::adoptFD(), RequestParse::body(), ResponseBuilder::build(), CgiHandler::buildEnvp(), Signals::checkCgiTimeouts(), Router::checkErrorStatus(), ClientConnection::clearBuffer(), ClientConnection::ClientConnection(), ClientConnection::ClientConnection(), ClientConnection::completedRequest(), Router::computeResolvedPath(), Dispatcher::dispatch(), ResponseBuilder::errorPageConfig(), AutoIndexHandler::getTemplatePath(), WebServer::gracefulShutdown(), AutoIndexHandler::handle(), DeleteHandler::handle(), StaticPageHandler::handle(), UploadHandler::handle(), ResponseBuilder::handleCgiOutput(), RequestParse::handleRawRequest(), RequestParse::headers(), Router::isAutoIndex(), Router::isCgi(), Router::isRedirect(), Router::isStaticFile(), Router::isUpload(), ServerSocket::listenConnections(), AutoIndexHandler::loadTemplate(), main(), ConfigParser::parseListenInterface(), WebServer::queueClientConnections(), WebServer::receiveRequest(), ClientConnection::recvData(), Signals::registerCgiProcess(), WebServer::removeClientConnection(), RequestParse::requestLine(), HttpRequest::reset(), HttpResponse::reset(), Router::resolve(), ResponseBuilder::responseWriter(), WebServer::runServer(), UploadHandler::saveFile(), ClientConnection::sendData(), WebServer::sendResponse(), ServerSocket::ServerSocket(), ServerSocket::ServerSocket(), Signals::setupHandlers(), Signals::signalHandle(), CgiHandler::startAsync(), WebServer::startServer(), ServerSocket::startSocket(), WebServer::sweepCgiTimeouts(), Signals::unregisterCgiProcess(), RequestParse::uri(), WebServer::WebServer(), ClientConnection::~ClientConnection(), ServerSocket::~ServerSocket(), and WebServer::~WebServer().
levelToString()
const std::string Logger::levelToString (LogLevel level) const private
Converts a LogLevel enum value to its string label.
Parameters
level The log severity level.
Returns
Corresponding string ("DEBUG", "INFO", etc.).
Definition at line 84 of file Logger.cpp.
{
    switch (level)
    {
        case DEBUG:
            return "DEBUG";
        case INFO:
            return "INFO";
        case WARNING:
            return "WARNING";
        case ERROR:
            return "ERROR";
        case CRITICAL:
            return "CRITICAL";
        default:
            return "UNKNOWN";
    }
}
References CRITICAL, DEBUG, ERROR, INFO, and WARNING.
Referenced by log().
log()
void Logger::log (LogLevel level, const std::string & message)
Writes a log entry with timestamp, level, and message.
Outputs to console depending on DEV mode:
DEV = 0: only INFO and higher.
DEV = 1: all levels. Always writes to the log file if open.
Definition at line 51 of file Logger.cpp.
{
    std::time_t now = time(0);
    tm* timeinfo = localtime(&now);
    char timestamp[20];
    std::strftime(timestamp, sizeof(timestamp), "%Y-%m-%d %H:%M:%S", timeinfo);
    std::ostringstream logEntry;
    logEntry << "[" << timestamp << "] "
                << levelToString(level) << ": " << message
                << std::endl;
    // Console output
    if (DEV == 0 && level >= INFO)
        std::cout << logEntry.str();
    else if (DEV == 1)
        std::cout << logEntry.str();
    // File output
    if (_logFile.is_open())
    {
        _logFile << logEntry.str();
        _logFile.flush();
    }
}
References _logFile, DEV, INFO, and levelToString().
Referenced by ServerSocket::acceptConnections(), ClientConnection::adoptFD(), RequestParse::body(), ResponseBuilder::build(), CgiHandler::buildEnvp(), Signals::checkCgiTimeouts(), Router::checkErrorStatus(), ClientConnection::clearBuffer(), ClientConnection::ClientConnection(), ClientConnection::ClientConnection(), ClientConnection::completedRequest(), Router::computeResolvedPath(), Dispatcher::dispatch(), ResponseBuilder::errorPageConfig(), AutoIndexHandler::getTemplatePath(), WebServer::gracefulShutdown(), AutoIndexHandler::handle(), DeleteHandler::handle(), StaticPageHandler::handle(), UploadHandler::handle(), ResponseBuilder::handleCgiOutput(), RequestParse::handleRawRequest(), RequestParse::headers(), Router::isAutoIndex(), Router::isCgi(), Router::isRedirect(), Router::isStaticFile(), Router::isUpload(), ServerSocket::listenConnections(), AutoIndexHandler::loadTemplate(), main(), ConfigParser::parseListenInterface(), WebServer::queueClientConnections(), WebServer::receiveRequest(), ClientConnection::recvData(), Signals::registerCgiProcess(), WebServer::removeClientConnection(), RequestParse::requestLine(), HttpRequest::reset(), HttpResponse::reset(), Router::resolve(), ResponseBuilder::responseWriter(), WebServer::runServer(), UploadHandler::saveFile(), ClientConnection::sendData(), WebServer::sendResponse(), ServerSocket::ServerSocket(), ServerSocket::ServerSocket(), Signals::setupHandlers(), Signals::signalHandle(), CgiHandler::startAsync(), WebServer::startServer(), ServerSocket::startSocket(), WebServer::sweepCgiTimeouts(), Signals::unregisterCgiProcess(), RequestParse::uri(), WebServer::WebServer(), ClientConnection::~ClientConnection(), ServerSocket::~ServerSocket(), and WebServer::~WebServer().
Member Data Documentation
_logFile
std::ofstream Logger::_logFile private
Definition at line 25 of file Logger.hpp.
Referenced by log(), Logger(), and ~Logger().
The documentation for this class was generated from the following files:
utils/Logger.hpp
utils/Logger.cpp