Webservinho: utils/string_utils.hpp File Reference
string_utils.hpp File Reference
Collection of inline string utility functions used across Webservinho.
#include <string>
#include <sstream>
#include <vector>
#include <algorithm>
#include <cctype>
#include <cstdlib>
#include <iomanip>
Functions
static std::string getFileExtension (const std::string &path)
Extracts the file extension from a path, including the dot.
static bool hasParentTraversal (const std::string &s)
Checks if a path string contains parent directory traversal (..) sequences.
static std::string joinPaths (const std::string &base, const std::string &sub)
Joins two path segments, ensuring correct slash placement.
std::string lTrim (const std::string &str)
Removes leading whitespace characters from a string.
std::string rTrim (const std::string &str)
Removes trailing whitespace characters from a string.
std::vector< std::string > split (const std::string &str, const std::string &sep)
Splits a string by a given separator substring.
bool startsWith (const std::string &s, const std::string &prefix)
Checks whether a string starts with a given prefix.
int stringToHex (const std::string &str)
Converts a hexadecimal string into an integer.
std::string toLower (const std::string &str)
Converts a string to lowercase.
template<typename T >
std::string toString (T value)
Converts any printable type to a string representation.
std::string toUpper (const std::string &str)
Converts a string to uppercase.
std::string trim (const std::string &str)
Removes leading and trailing whitespace characters from a string.
static std::string trim_copy (const std::string &s)
Returns a copy of a string with surrounding spaces and tabs removed.
static std::string uriEncode (const std::string &s)
Encodes a string for safe inclusion in a URI (percent-encoding).
Detailed Description
Collection of inline string utility functions used across Webservinho.
This header provides lightweight helpers for string manipulation, trimming, case conversion, splitting, joining, and validation.
All functions are inline for performance and are compatible with C++98.
Definition in file string_utils.hpp.
Function Documentation
getFileExtension()
static std::string getFileExtension (const std::string & path) inline static
Extracts the file extension from a path, including the dot.
Returns
The extension (e.g., ".html") or an empty string if none.
Definition at line 178 of file string_utils.hpp.
{
    std::string::size_type dotPos = path.find_last_of('.');
    if (dotPos == std::string::npos)
        return ("");
    std::string::size_type slashPos = path.find_last_of('/');
    if (slashPos != std::string::npos && dotPos < slashPos)
        return ("");
    return (path.substr(dotPos));
}
Referenced by Router::hasCgiExtension().
hasParentTraversal()
static bool hasParentTraversal (const std::string & s) inline static
Checks if a path string contains parent directory traversal (..) sequences.
Definition at line 147 of file string_utils.hpp.
{
    if (s.find("/../") != std::string::npos)
        return (true);
    if (s.size() >= 3 && s.substr(0, 3) == "../")
        return (true);
    if (s.size() >= 3 && s.substr(s.size() - 3) == "/..")
        return (true);
    return (false);
}
Referenced by Router::resolve().
joinPaths()
static std::string joinPaths (const std::string & base, const std::string & sub) inline static
Joins two path segments, ensuring correct slash placement.
Parameters
base Base path.
sub Subdirectory or file name.
Returns
Combined path with normalized slashes.
Definition at line 131 of file string_utils.hpp.
{
    if (base.empty())
        return (sub);
    if (sub.empty())
        return (base);
    if (base[base.size() - 1] == '/' && sub[0] == '/')
        return (base + sub.substr(1));
    else if (base[base.size() - 1] != '/' && sub[0] != '/')
        return (base + '/' + sub);
    else
        return (base + sub);
}
Referenced by Router::computeResolvedPath().
lTrim()
std::string lTrim (const std::string & str) inline
Removes leading whitespace characters from a string.
Definition at line 23 of file string_utils.hpp.
{
    std::string::size_type start = 0;
    while (start < str.size()
        && std::isspace(static_cast<unsigned char>(str[start])))
    {
        ++start;
    }
    return (str.substr(start));
}
Referenced by trim().
rTrim()
std::string rTrim (const std::string & str) inline
Removes trailing whitespace characters from a string.
Definition at line 35 of file string_utils.hpp.
{
    if (str.empty())
        return (str);
    std::string::size_type end = str.size() - 1;
    while (end != std::string::npos
        && std::isspace(static_cast<unsigned char>(str[end])))
    {
        if (end == 0)
            return ("");
        --end;
    }
    return (str.substr(0, end + 1));
}
Referenced by trim().
split()
std::vector< std::string > split (const std::string & str, const std::string & sep) inline
Splits a string by a given separator substring.
Parameters
str The input string.
sep The separator substring.
Returns
A vector containing all tokens.
Definition at line 80 of file string_utils.hpp.
{
    std::vector<std::string> tokens;
    size_t start = 0;
    size_t end = str.find(sep);
    while (end != std::string::npos)
    {
        tokens.push_back(str.substr(start, end - start));
        start = end + sep.length();
        end = str.find(sep, start);
    }
    tokens.push_back(str.substr(start));
    return (tokens);
}
Referenced by RequestParse::requestLine().
startsWith()
bool startsWith (const std::string & s, const std::string & prefix) inline
Checks whether a string starts with a given prefix.
Definition at line 120 of file string_utils.hpp.
{
    return s.size() >= prefix.size() &&
            std::equal(prefix.begin(), prefix.end(), s.begin());
}
Referenced by ServerConfig::matchLocation().
stringToHex()
int stringToHex (const std::string & str) inline
Converts a hexadecimal string into an integer.
Returns
The converted value, or -1 if conversion fails.
Definition at line 99 of file string_utils.hpp.
{
    std::istringstream iss(str);
    int value;
    iss >> std::hex >> value;
    if (iss.fail() || !iss.eof())
        return (-1);
    return (value);
}
Referenced by RequestParse::bodyChunked().
toLower()
std::string toLower (const std::string & str) inline
Converts a string to lowercase.
Definition at line 52 of file string_utils.hpp.
{
    std::string result = str;
    std::transform(result.begin(), result.end(), result.begin(),
                    (int(*)(int)) std::tolower);
    return (result);
}
Referenced by StaticPageHandler::detectMimeType(), HttpRequest::getHeader(), ResponseBuilder::handleCgiOutput(), HttpRequest::hasHeader(), RequestParse::headers(), and HttpRequest::removeHeader().
toString()
template<typename T > std::string toString (T value) inline
Converts any printable type to a string representation.
Definition at line 112 of file string_utils.hpp.
{
    std::ostringstream oss;
    oss << value;
    return oss.str();
}
Referenced by ServerSocket::acceptConnections(), ClientConnection::adoptFD(), RequestParse::body(), ResponseBuilder::build(), CgiHandler::buildEnvp(), Signals::checkCgiTimeouts(), Router::checkErrorStatus(), ClientConnection::completedRequest(), Dispatcher::dispatch(), AutoIndexHandler::handle(), UploadHandler::handle(), ResponseBuilder::handleCgiOutput(), RequestParse::handleRawRequest(), ResponseBuilder::handleStaticPageOutput(), ServerSocket::listenConnections(), AutoIndexHandler::loadTemplate(), WebServer::queueClientConnections(), WebServer::receiveRequest(), ClientConnection::recvData(), Signals::registerCgiProcess(), WebServer::removeClientConnection(), ClientConnection::sendData(), WebServer::sendResponse(), ServerSocket::ServerSocket(), CgiHandler::startAsync(), WebServer::startServer(), WebServer::sweepCgiTimeouts(), Signals::unregisterCgiProcess(), ClientConnection::~ClientConnection(), and ServerSocket::~ServerSocket().
toUpper()
std::string toUpper (const std::string & str) inline
Converts a string to uppercase.
Definition at line 61 of file string_utils.hpp.
{
    std::string result = str;
    std::transform(result.begin(), result.end(), result.begin(),
                    (int(*)(int)) std::toupper);
    return (result);
}
trim()
std::string trim (const std::string & str) inline
Removes leading and trailing whitespace characters from a string.
Definition at line 70 of file string_utils.hpp.
{
    return (rTrim(lTrim(str)));
}
References lTrim(), and rTrim().
Referenced by ResponseBuilder::handleCgiOutput(), and RequestParse::headers().
trim_copy()
static std::string trim_copy (const std::string & s) inline static
Returns a copy of a string with surrounding spaces and tabs removed.
Definition at line 162 of file string_utils.hpp.
{
    size_t a = 0;
    size_t b = s.size();
    while (a < b && (s[a] == ' ' || s[a] == '\t'))
        a++;
    while (b > a && (s[b - 1] == ' ' || s[b - 1] == '\t'))
        b--;
    return (s.substr(a, b - a));
}
Referenced by UploadHandler::extractBoundary(), and UploadHandler::parsePart().
uriEncode()
static std::string uriEncode (const std::string & s) inline static
Encodes a string for safe inclusion in a URI (percent-encoding).
Parameters
s The input string.
Returns
The URI-encoded version of the string.
Definition at line 195 of file string_utils.hpp.
{
    std::ostringstream oss;
    for (size_t i = 0; i < s.size(); ++i)
    {
        unsigned char c = s[i];
        if (isalnum(c) || c == '-' || c == '_' || c == '.' || c == '~')
            oss << c;
        else
            oss << '%' << std::uppercase << std::hex << std::setw(2)
                << std::setfill('0') << int(c);
    }
    return oss.str();
}
Referenced by AutoIndexHandler::handle().