#!/usr/bin/python3
import cgi

print("Content-Type: text/html\r\n\r\n")
form = cgi.FieldStorage()
name = form.getfirst("name", "Anonymous")

print(f"""
<html>
<body>
<h1>Hello, {name}!</h1>
<p>This message was generated by a Python CGI script.</p>
<a href="/">Back to Home</a>
</body>
</html>
""")